### ISSUE TITLE
TabExpansion ceased to work

### ISSUE THREAD

**Issue by lalibi** [psake/psake#101]
I recently updated from version 4.2.0.1 to 4.3.0.1 and TabExpansion no longer works. It seems that the `WriteDocumentation` (`Write-Documentation`) function has a slighter different implementation.

Possibly the reason is the use of `format-list` (in v4.3.1.0) instead of the former `format-table`

**Comment by dlwyatt** [comment]
Are you trying to tab-complete the WriteDocumentation function from your build script?  That function isn't exported.  It's called when you use the -Docs or -DetailedDocs switch when calling Invoke-Psake.

If your problem is something else, please provide more details.

**Comment by lalibi** [comment]
That was a long time ago actually. It works now.

**Comment by gep13** [comment]
@lalibi thanks for getting back to us! :smile:
