### ISSUE TITLE
Override Write cmdlets (e.g. Write-Verbose)

### ISSUE THREAD

**Issue by heaths** [psake/psake#111]
Calling write-verbose, write-warning, and write-error do nothing, at least, when invoking psake.bat from a chocolatey install, but it shouldn't matter how `invoke-psake` gets called since it's already writing its own verbose messages when passing -v to psake.

Chocolatey scripts themselves to this by overriding those `write-*` cmdlets so that we can write information at different levels when, for example, debugging psake scripts.

**Comment by dermeister0** [comment]
It works if I set $InformationPreference in task, but need to have a global option.

    Task test `
    {
        $InformationPreference = 'Continue'
        Write-Information 'HELLO'
    }

**Comment by dermeister0** [comment]
Related task: #65
