### ISSUE TITLE
DOC question; psake v4.4.1 on nuget but no tag/release and here it is the 'next' milestone?

### ISSUE THREAD

**Issue by AnneTheAgile** [psake/psake#129]
hi! I am about to start using psake and would like the nuget clarified, is it 4.4.1 and then this repo is 4.4.2? If so then we need a tag/release for 4.4.1, right?
ty!
AnneTheAgile
1.[] ; ; ; ; ; X.Releases · psake/psake ; ; https://github.com/psake/psake/releases
2.[] Nov. 19, 2014; ; ; ; ; X.NuGet Gallery | psake 4.4.1 ; ; http://www.nuget.org/packages/psake

**Comment by damianh** [comment]
Tagged. https://github.com/psake/psake/tree/v4.4.1
