### ISSUE TITLE
Problem running build script on the first attempt

### ISSUE THREAD

**Issue by exeraph** [psake/psake#139]
Hello!

Currently I'm witnessing something strange:
**My script works only after the second attempt.**

![capture](https://cloud.githubusercontent.com/assets/13888804/9386758/4d6a777c-475d-11e5-8e5a-de57a6802435.PNG)

**Contents of build.ps1**

Import-Module .\tools\psake.psm1
Invoke-psake default.ps1 -parameters @{"version"="1.30.0.0";"repository"="C:\path\to\repository\"}

Any ideas how to fix this?

Thank you in advance!

**Comment by gep13** [comment]
@exeraph were you able to resolve this issue?  Sorry for not getting back to you sooner!
