### ISSUE TITLE
Wrong exitcode of psake.cmd on errors

### ISSUE THREAD

**Issue by ulrichb** [psake/psake#140]
I want to restart #58 with a very simple repro sample.

Given the following psake script.

```
Task DoIt {
   "doing..."
}

Task FailIt {
   "failing..."
   throw "lol"
}
```

Invoking `psake.cmd build.ps1 DoIt && echo ====== SUCCESS ======` gives the following output as expected.

```
Executing DoIt
doing...

Build Succeeded!

----------------------------------------------------------------------
Build Time Report
----------------------------------------------------------------------
Name   Duration
----   --------
DoIt   00:00:00.0275158
Total: 00:00:00.2430415
====== SUCCESS ======
```

But invoking `psake.cmd build.ps1 FailIt && echo ====== SUCCESS ======` gives the following output.

```
Executing FailIt
failing...
Error: 28.08.2015 13:18:55:
At C:\[...]\build.ps1:7 char:4 +    throw "lol" +    ~~~~~~~~~~~ [<<==>>] Exception: lol
====== SUCCESS ======
```

=> The `====== SUCCESS ======` line shows that the exit code is zero too.

Note: I further analyzed this and mentioned that the `$psake.build_success` value in [psake.cmd](https://github.com/psake/psake/blob/eb1f763e5329d59397080da4cb6030f117e64602/psake.cmd#L10) is correct (`True` in the first case `False` in the second). So the problem seems to be the `exit 1`.

**Comment by gep13** [comment]
@ulrichb are you in a position to provide a PR to correct this issue? Thanks!

**Comment by alexandear** [comment]
You need rename `psake.cmd` to `psake.bat` and everything will work as expected.

**Comment by drinkbird** [comment]
I can confirm that this is still the case

**Comment by chrisoldwood** [comment]
You probably need to use `call psake.cmd` if you want the `&&` to behave as you expect.

For example, create a batch file (`Test.cmd`) with:
```
@echo off
exit /b 1
```

Then invoke `Test.cmd && echo ...` with and without `call`:

```
> test.cmd && echo Success!
Success!
>call test.cmd && echo Success!

```
