### ISSUE TITLE
Publish Psake on PowerShellGallery

### ISSUE THREAD

**Issue by olegsych** [psake/psake#143]
I'd like to consume Psake from the [PowerShellGallery](https://www.powershellgallery.com). Can it be published there?

**Comment by gep13** [comment]
I am certainly not against this happening, but this is not something that I have done before.

If this is something that you are familiar with, and can help with the steps required to do this, then I will gladly get it done.  Thanks!

**Comment by olegsych** [comment]
I've recently figured out how to do this for [posh-vs](https://github.com/olegsych/posh-vs). In a nutshell, I had to:
- Create a PowerShell [module manifest](https://github.com/olegsych/posh-vs/blob/master/posh-vs.psd1). I created a template with `New-ModuleManifest` and hand-edited it to leave only what seemed relevant. 
- Use `Publish-Module` command to push the package to the PowerShell Gallery. 
You can find more details in the [readme](https://github.com/olegsych/posh-vs#development).

Ideally, I'd want to automate it with AppVeyor, but haven't spent the time yet.

**Comment by RaYell** [comment]
PowerShell Gallery is a slightly modified version of NuGet server. You can work with it almost the same way as with NuGet, although the cmdlets that @olegsych mentioned are usually an easier way.

More details can be found [here](https://www.powershellgallery.com/GettingStarted?section=FAQ)

**Comment by rkeithhill** [comment]
+1.  These days, the popular PowerShell modules should be downloadable via the PowerShell Gallery and the PSV5 built-in install-module command e.g. I want to install this module like so:
```powershell
Install-Module PSake -Scope CurrentUser
```

**Comment by dlwyatt** [comment]
I can take care of this.  Main difference is that we'd need a module manifest (which is a good idea anyway), and the version number of the module should come from there, not where it's currently hard-coded in psake.psm1:

```posh
# This line:
$psake.version = "4.5.0" # contains the current version of psake

# would become this:
$psake.version = [string]$ExecutionContext.SessionState.Module.Version
```

**Comment by gep13** [comment]
@dlwyatt If you go pick this up, can I get you to record the steps that you need to take, and put them into the BitBucket repo, so that others can follow the same steps, if required?  Also, if you need to create an account to publish to the Gallery, can you use the shared Microsoft Account which you can find in the KeePass database?

**Comment by rkeithhill** [comment]
Maybe it could even be, I don't know, a PSake publish script.  `<ducks for cover/>`  :-)

**Comment by dlwyatt** [comment]
I once asked about setting up a "team" key for a project without having to share one's personal API key (which grants access to all of your projects), but never really got anywhere with it.  I'd just be publishing with my own API key, which would not go into KeePass.  Instead, I can just add other users to the project on the Gallery, at which point anyone on that list can use their own API keys as well.

**Comment by rkeithhill** [comment]
If a module is published with different keys would that mess up `Update-Module`?

**Comment by gep13** [comment]
>@dlwyatt said...
Instead, I can just add other users to the project on the Gallery, at which point anyone on that list can use their own API keys as well.

Ok, no worries.  If you could record the steps required to do the gallery submission, that would be good though, as others would be able to follow along when a new release is available, and that way it isn't down to you each time :+1:

**Comment by gep13** [comment]
>@rkeithhill said...
Maybe it could even be, I don't know, a PSake-based publish script. <ducks for cover/> :-)

Yes, I think that would make sense as well.  Documented steps would be the bear minimum, with a script being the ideal :smile:

**Comment by dlwyatt** [comment]
> If a module is published with different keys would that mess up Update-Module?

Nope, no problem.  The first time a project is published, it's owned by the user who did it.  Then that user can add other project owners who are also allowed to publish.  Doesn't matter which key / account is used to push out each new version; they all just go into the project at that point.

**Comment by dlwyatt** [comment]
I've just added a quick initial version of the module manifest:  https://github.com/psake/psake/blob/master/psake.psd1 .  Description, Tags, and IconUri are still to be filled in, but this has the essentials that should get us ready to publish to the gallery.

**Comment by rkeithhill** [comment]
I think you need a `Description` to publish don't you?  Seems like I remember publish failing when there wasn't a description.  Also, probably ought to add at least few tags `Build`, `Task` ??

**Comment by dlwyatt** [comment]
I'm not sure what's required by the gallery.  I intended to have all of that filled out before publishing either way.  :)

**Comment by dlwyatt** [comment]
Updated with description (copied from the wiki) and a couple of tags.  IconUri we can add whenever #148 is ready.

**Comment by dlwyatt** [comment]
I've tweaked psake.psm1 to load the version from the module manifest, so we're not duplicating that (and potentially forgetting to update it in one place or the other.)  Turned out to not be quite a simple as I'd hoped; the version of `$ExecutionContext.SessionState.Module` is still 0.0 when the psm1 file is initially being imported.  Test-ModuleManifest gets what we need, though.

https://github.com/psake/psake/commit/5d75a265f56784eae9b3c65a73dad64906116b36

**Comment by dlwyatt** [comment]
This should be ready to go, but I did have to make some changes to psake.psm1 in the master branch.  Since there were already unreleased changes there (https://github.com/psake/psake/releases/tag/untagged-1b721ac2b6246590b677) , the actual publish to the gallery will happen whenever you're ready to pull the trigger on v4.6.0.

**Comment by rkeithhill** [comment]
Any ETA on 4.6.0?  

We are contemplating taking on [dependency on PSake for the PowerShell extension for VSCode](https://github.com/PowerShell/vscode-powershell/issues/107).  We would provide a `build/publish` script that is PSake based that would help folks publish PowerShell modules to the PowerShell Gallery.  We are targeting late March for this release - assuming this support makes it into that release it would be nice to tell folks all they need to do to install psake is run `install-module psake -scope CurrentUser`.

**Comment by gep13** [comment]
@rkeithhill I am juggling a few things just now, but I would hope to get this done before the middle of March.

**Comment by rkeithhill** [comment]
Cool!  Thanks for the update.

**Comment by rkeithhill** [comment]
FYI, we published the [PowerShell VSCode extension](https://t.co/gDEkrCKQJD) today with instructions telling folks to install PSake using the PowerShell gallery.  So hopefully you can still make the middle of March.  Not to put any pressure on you or anything.  :-)

**Comment by sweeneyrobb** [comment]
hah! @rkeithhill :+1:

**Comment by dlwyatt** [comment]
The changes I had to make to the psm1 file are very minor.  I could just make a quick branch based on the 4.5 release and publish that, if it helps.

**Comment by rkeithhill** [comment]
If you want to see PSake in action with Visual Studio Code and the PowerShell extension, check out this [blog post](https://rkeithhill.wordpress.com/2016/03/10/preview-of-module-build-and-publish-with-visual-studio-code-and-the-powershell-extension/).

**Comment by gep13** [comment]
Ok, I "think" I have now done this.  And it is available here:

https://www.powershellgallery.com/packages/psake/4.6.0

Can someone check it out, and make sure it is working as expected?  Thanks!

**Comment by gep13** [comment]
@dlwyatt what is your username on Powershell Gallery?  I can get you added an as owner.

**Comment by dlwyatt** [comment]
It's just dlwyatt, same as here.

**Comment by dlwyatt** [comment]
Also, just installed from the gallery and ran one of my build scripts; seems to be working fine.  :)

**Comment by gep13** [comment]
>@dlwyatt said...
It's just dlwyatt, same as here.

Just added you as owner.

>@dlwyatt said...
Also, just installed from the gallery and ran one of my build scripts; seems to be working fine. :)

Woot!

**Comment by rkeithhill** [comment]
The PowerShell extension for Visual Studio Code example works with this release as well.  Thanks!

**Comment by gep13** [comment]
@rkeithhill that is great to hear! :smile_cat:
