### ISSUE TITLE
Add support for colors in mintty terminal

### ISSUE THREAD

**Issue by sszachow** [psake/psake#144]
When running psake in mintty terminal (for instance shipped with Git for Windows), output completely lacks colors.

I know that colors are produced in cmd.exe, but it would be cool to see colorful output in mintty for at least:
-Task names
-Errors produced by paske

It should be possible to detect in psake that it runs under mintty and in that case produce text with different color than default.

**Comment by gep13** [comment]
@sszachow I am not a user of mintty, and I wouldn't know where to start in getting this implemented, but I would be happy to review a PR, and get this pulled in if this is something that you wanted to work on.  Thanks!

**Comment by whut** [comment]
I think we could implement natively [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) if running under Cygwin/MSYS/Git for Window, but in the interim you can use the [winpty](https://github.com/rprichard/winpty) that is shipped with beforementioned environments. 

**Example**

```bash
winpty powershell.exe ./psake.ps1
```

**Comment by sszachow** [comment]
Hi @whut,

You are right, it works pretty well with psake.
I think we can close this issue. Adding ANSI escape codes would solve problem only partially. There is no support for such codes for instance in msbuild.
If MSYS becomes more popular (and it should), we could add trick with winpty to documentation.

Cheers

**Comment by whut** [comment]
Just a side note: the reverse, that is printing colorful output using ANSI escape codes, is now natively supported inside "Command Prompt" on Windows 10. Check here http://www.nivot.org/blog/post/2016/02/04/Windows-10-TH2-%28v1511%29-Console-Host-Enhancements, documented here: https://msdn.microsoft.com/en-us/library/mt638032.aspx
