### ISSUE TITLE
Need new Icon for psake

### ISSUE THREAD

**Issue by gep13** [psake/psake#148]
Something that can be used on NuGet.org and Chocolatey.org, and anywhere else that psake is published.

Any ideas?

**Comment by sweeneyrobb** [comment]
With the mention of publishing on PSGallery i thought i'd give this a shot. I pulled some colors off of the original logo. simple sake cups (with PowerShell logo), stacked (kinda representing the stacking of tasks in PSake).

![psake-icon](https://cloud.githubusercontent.com/assets/301574/13507668/8153e06c-e138-11e5-84ed-d5029a53f806.jpg)

**Comment by gep13** [comment]
Ooo, I really like this idea!  This would get a thumbs up from me!

@damianh @dlwyatt what are your thoughts on these?

**Comment by dlwyatt** [comment]
I'm exactly the wrong person to ask about aesthetics.  I have the artistic judgment and skills of a blind, drunk yak.  :P

**Comment by gep13** [comment]
Ha ha :smile: 

Let's put it this way, The above is far better than anything I would be able to come up with.  So if there are no other takers, I am happy to run with them.  I prefer the left hand side one.

**Comment by sweeneyrobb** [comment]
@gep13 I'll put together an set of images with common sizes for chocolatey, nuget, psgallery, etc. Is there a place I should upload this collateral to?

**Comment by gep13** [comment]
@sweeneyrobb yes, let's put these over here:

https://github.com/psake/graphics

**Comment by gep13** [comment]
@sweeneyrobb perhaps something like this:

https://github.com/cake-build/graphics

Where we separate out the source files, with the usable media.  What do you think?

**Comment by sweeneyrobb** [comment]
@gep13 yep, that's the goal.

**Comment by sweeneyrobb** [comment]
@gep13

i just added a PR (https://github.com/psake/graphics/pull/1) in the [psake/graphics](https://github.com/psake/graphics/) repo. Let me know if there are any issues.

**Comment by damianh** [comment]
I like! :)

**Comment by RomanBlyshchyk** [comment]
Looks awesome !!

**Comment by gep13** [comment]
@sweeneyrobb thanks again for doing this! I really like the new icons :smile:
