### ISSUE TITLE
Tests dotNet4.* use not quite right Assert's

### ISSUE THREAD

**Issue by nightroman** [psake/psake#150]
Tests dotNet4.\* use these Assert conditions
- _dotNet4.5.1_should_pass.ps1_ uses `$output -NotLike "12.0"`
- _dotNet4.6.1_should_pass.ps1_ uses `$output -NotLike "14.0"`
- _dotNet4.6_should_pass.ps1_ uses `$output -NotLike "14.0"`

These conditions are not quite right, they may get true if output is not expected:

```
$output = 'foo bar'
$output -NotLike "12.0" # True
$output -NotLike "14.0" # True
```

On the other hand, they get false when the output is one of expected:

```
$output = '12.0'
$output -NotLike "12.0" # False

$output = '14.0'
$output -NotLike "14.0" # False
```

The correct expressions presumably are (not tested)
- _dotNet4.5.1_should_pass.ps1_ uses `$output -Like "12.0*"`
- _dotNet4.6.1_should_pass.ps1_ uses `$output -Like "14.0*"`
- _dotNet4.6_should_pass.ps1_ uses `$output -Like "14.0*"`

**Comment by gep13** [comment]
@nightroman yes, I think I would agree with your interpretation.  Would you be in a position to submit a pull request to correct this?

Thanks!

**Comment by nightroman** [comment]
I just wated to draw your attention to the issue.

As for the tests, there is something else. What if a particular tool / framework is not istalled? The tests in their current form will fail. They should not. If a tool is not present then tests should skip their checks.

**Comment by nightroman** [comment]
Please take a look at how it is done in the similar tests [Use.test.ps1](https://github.com/nightroman/Invoke-Build/blob/master/Tests/Use.test.ps1).
