### ISSUE TITLE
Invoke-psake with option to return documentation should return objects instead of formated string

### ISSUE THREAD

**Issue by mabead** [psake/psake#153]
Invoke-psake already has options (-docs, -detailedDocs) to display the list of Task defined in a psake script. Unfortunately, these options return formatted strings:

    if ($showDetailed) {
        $docs | sort 'Name' | format-list -property Name,Alias,Description,"Depends On",Default
    } else {
        $docs | sort 'Name' | format-table -autoSize -wrap -property Name,Alias,"Depends On",Default,Description
    }

Since the information on the tasks is already formatted as a list/table, the script that invokes -docs or -detailedDocs can't do anything else than print this information to the console.

In order to be able to be to do something with this data from the outside, there should be an option to return the objects themselves (ex: -structuredDocs). For example, we could do:

    if ($showDetailed) {
        $docs | sort 'Name' | format-list -property Name,Alias,Description,"Depends On",Default
    } elseif ($showSummary) {
        $docs | sort 'Name' | format-table -autoSize -wrap -property Name,Alias,"Depends On",Default,Description
    } else {
        $docs
    }

I am looking to have this feature because I want to be able to print a tree of the task dependencies in my build script. This will make it easier for my users to know which targets are available AND how they relate to each other... with minimal mental effort ;)

What do you think about this feature? From my opinion, it only opens up the door for people to do fun stuff with this metadata.

**Comment by mabead** [comment]
Here is an example of what I want to do in the end with the data returned by -structuredDocs. From an external script, I want to be able to print the tasks hierarchy. This will make it much easier for my users to know the available tasks:

    The following displays the available tasks that you can provide to -taskList. The hierarchy of the tasks is also displayed.
    
      Default
        SetupMachine
          InstallDependencies
          InstallIisSslCertificates
        Clean
          CleanNugetPackages
          CleanSolutions
          CleanArtifacts
        Compile
          RestoreNugetPackages
          CompileSolutions
        Test
          SetupTests
          RunTests
            RunApiTests
            RunUnitTests
            RunIntegrationTests

**Comment by gep13** [comment]
@mabead I think this makes a lot of sense.  I would happily accept a PR to include this functionality.

**Comment by mabead** [comment]
@gep13 Great. I will do it later this week. Thanks.

**Comment by gep13** [comment]
@mabead nice one! :+1:

**Comment by mabead** [comment]
The pull request is here: 

https://github.com/psake/psake/pull/156

This is my fIrst PR in github. So please let me know if I could have done something better.

**Comment by sweeneyrobb** [comment]
@mabead @gep13 

just a comment here. isn't this overloading a bit of what `Invoke-psake` is doing? i think it's a great idea to return objects to do some more fancy stuff. but, adding adding more and more flags to the `Invoke-psake` seems that we are building up a more intricate state machine. if showdetailed, show summary, else return objects.

seems like creating a function/cmdlet that can return the execution tree would be a bit more versatile. `Invoke-psake` doesn't do what it's titled when provided the docs flags. i know even internally this can be useful to call if one wanted to do any validation of the script in a pre scriptblock.

i don't suggest we change the current behavior. I'm sure many are using the current doc flags on `Invoke-psake` i just think it would be nice to reduce additional state branches.

i'm running into a similar situation adding the `-parallelDepends` argument to the `Task` function. i could simply add these into the normal array of dependencies and add a `mode` property/hashtable entry to flag the dependencies as Parallel or Serial but i want to avoid the state `mode` would introduce.

any thoughts on this would definitely help me on issue #97.

**Comment by mabead** [comment]
@sweeneyrobb 

These are great comments. I had the same alarm ringing in my head. This flags does not really belong to Invoke-psake. I will instead create a new function like Get-ScriptTasks. In order to preserve backward compatibility, I will leave -docs and -detailedDocs inside Invoke-psake but I agree with that it is not where they belong. 

When -docs and -detailedDocs are used, it will internally call Get-ScriptTasks and then simply format the results.

Thanks for the great feedback.

@gep13 You can forget about my pull request for now. I will start over with these recommendations in mind.

**Comment by mabead** [comment]
Out of curiosity, why do we document the psake functions into an external xml file? I feel it much more painful than when using comment based help.

**Comment by dlwyatt** [comment]
I wasn't around for that decision, but external XML help files have two advantages:

- They can be localized for multiple languages; comment-based help cannot.
- They can be hosted online and updated with the Update-Help cmdlet.

We're not actually doing either of those things, but there you go.

**Comment by sweeneyrobb** [comment]
@mabead thanks!

the docs arguments really bug me as they change the behavior of the function completely. early return and doesn't actually execute the script. i think adding a new cmdlet makes a bunch of sense.

Though, in your naming, and i know this isn't consistent anywhere else in psake, but, most libraries prefix their nouns with the technology. e.g. Get-SP* or Get-FTP*. Maybe this is a habit the psake project could also pick up? Using your example `Get-PSakeScriptTasks`. Just another food for thought :)

**Comment by mabead** [comment]
New pull request is here https://github.com/psake/psake/pull/157

**Comment by gep13** [comment]
@sweeneyrobb I like the idea of Get-Psake... as well :+1:

**Comment by mabead** [comment]
@sweeneyrobb @gep13 Same for me. I will rename it.

**Comment by mabead** [comment]
@dlwyatt Do you have any suggestion to generate the boiler plate MAML/XML for the documentation? Since lots of data is duplicated from the powershell function definition, I was wondering if you have any tool that can reflect the powershell functions and spit out a MAML skeleton that has to be filled later. 

I have see the [PowerShell CmdLet Editor](https://pscmdlethelpeditor.codeplex.com/) but I was looking for something more lightweight. Ideally a simple script.

**Comment by dlwyatt** [comment]
https://www.sapien.com/software/powershell_helpwriter is a new-ish tool which does pretty much exactly that.  You can thank June Blender for that one.  :)  It's not free, though, and personally, I have just been sticking to comment-based help in my modules.

**Comment by dlwyatt** [comment]
(Not at all lightweight, though.)

**Comment by mabead** [comment]
Comment based help was also perfect for me... until I wanted to contribute to psake ;)

**Comment by kapslockkaps** [comment]
I am getting below error in deploy.ps1 script,

 We are generating web.config through Psake automation.Exception: Cannot validate argument on parameter 'private:configFile'.Web.Config" did not return a result of True

15:13:10.297  +     Invoke-XmlPreprocess "$releaseArtifacts/$webName/Web.Config" $configurationE ...
15:13:10.297  +                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Cannot validate argument on parameter 'private:configFile'. The " Test-Path $_ -PathType Leaf " validation script for the argument with value "D:\GoAgent\pipelines\Dev\ReleaseArtifacts/MS/Web.Config" did not return a result of True. Determine why the validation script failed, and then try the command again. --> The " Test-Path $_ -PathType Leaf " validation script for the argument with value "D:\GoAgent\pipelines\Dev\ReleaseArtifacts/MS/Web.Config" did not return a result of True. Determine why the validation script failed, and then try the command again.

**Comment by motowilliams** [comment]
Where did this land? on v.4.8.0 I have -docs and -detailedDocs neither of which are objects that can be piped to Select etc.
