### ISSUE TITLE
Psake build task for VSTS

### ISSUE THREAD

**Issue by qetza** [psake/psake#154]
Hi,
This is not an issue but i didn't know how to contact the psake team :(

I've published a build task for VSTS that allow people to easily use psake build scripts, you can find the extension here:
https://marketplace.visualstudio.com/items?itemName=qetza.psake

Guillaume

**Comment by sweeneyrobb** [comment]
@qetza this is pretty awesome! The psake team seems a bit unresponsive. I have a pull request and some comments on issues that haven't been responded to either. There is an issue opened looking for a new maintainer. Seems as if the current one is challenged for time.

**Comment by sweeneyrobb** [comment]
@qetza i was thinking about this a bit longer. maybe you could add an entry into the project wiki?

**Comment by qetza** [comment]
@sweeneyrobb good idea, i'll do this this week.

**Comment by gep13** [comment]
@qetza this is a great idea!  Thanks for doing this.  In addition to adding this to the wiki, I would go one step further... Do you want to bring this repo into the psake organisation on GitHub?  If you do, I can get you added as a team member for the psake organisation, and give you full admin rights on the repo once it is moved over.  You will still be in full control of, the project will just have more visibility by belonging to the psake org.  What do you think?

**Comment by gep13** [comment]
@sweeneyrobb I think it is fair to say that my time is limited.  I shared my spare OSS time across multiple projects, and given that psake is a very mature project, there isn't as many things to do with it, therefore, it gets the least amount of my time.  That doesn't mean that it isn't important, just that it doesn't normally need as much of my time.

**Comment by gep13** [comment]
@qetza you might have noticed that @sweeneyrobb has created psake an icon, it would be great to see the icon added to the VSTS Task so that we can start getting the branding out there :smile: 

https://github.com/psake/graphics

**Comment by qetza** [comment]
@gep13 no problem to bring the repo in the psake organisation on GitHub :)
For the icon i didn't saw the graphics created by @sweeneyrobb, i'll update the extension to use these.

**Comment by gep13** [comment]
@qetza that is great news!  Let me know when you want to start the transfer of the repository, and I will get the necessary Team/Ownership created, so that you have the correct permissions, etc.

The icon has only just been created, so it is brand new :smile:

**Comment by qetza** [comment]
@gep13 i can do the transfer this week end and update the task with the new logo and links. Just tell me how to do it and how to rename the repo to be more compliant with the current naming :)

**Comment by gep13** [comment]
@qetza sorry for not getting back to you sooner about this!

You should be able to transfer the repo by following these instructions:

https://help.github.com/articles/transferring-a-repository/

Let me know if there is anything that I need to do.  In terms of naming convention, there are no hard and fast rules, so don't think that you have to change this, unless you really want to.

**Comment by gep13** [comment]
@qetza you should be receiving an email from GitHub soon.  Let me know when you get it, and we can continue the process.  Thanks!

**Comment by qetza** [comment]
@gep13 I'v received the email and accepted the invitation :)

**Comment by gep13** [comment]
@qetza ok, can you attempt the transfer again please?

**Comment by qetza** [comment]
@gep13 Done :)
I'll update the task for url and icons tomorrow an publish a new version on the vsts marketplace

**Comment by gep13** [comment]
@qetza that is great! Thank you for sticking with me through getting this set up, I really appreciate it.  I think we can go ahead and close this issue for now.

**Comment by qetza** [comment]
New version is now released: https://marketplace.visualstudio.com/items?itemName=qetza.psake
