### ISSUE TITLE
reporting build problems to TeamCity

### ISSUE THREAD

**Issue by dealproc** [psake/psake#160]
Most likely this is going to trigger a PR from the core maintainers, but according to the TeamCity docs, the proper method to fail the build is now by calling `##teamcity[buildProblem description="Build script failure.  Examine logs for further information."]`.  In the TeamCity helper method(s), there doesn't seem to be anything available to support this.

Is the project being actively maintained enough to submit and have a PR accepted?

**Comment by dlwyatt** [comment]
Yep, submit away.  :)  This is the wrong repository for the TeamCity helpers, though, so I'll close the issue here, and you can open a PR over in https://github.com/psake/psake-contrib .

**Comment by gep13** [comment]
@dealproc yip, I will happily accept any PR's into that repo, and publish new packages when required.
