### ISSUE TITLE
msbuild lc.exe is missing

### ISSUE THREAD

**Issue by stashev** [psake/psake#161]
Hello
Just moved to net 4.6...

Using 
`Exec { msbuild $solution /p:Configuration=Debug /p:VisualStudioVersion=14.0 /m}`
cause error:
 C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.targets(2428,5): error MSB3086: Task could not find "LC.exe" using the SdkToolsPath "" or the regi
try key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the c
rrect processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed [C:\Users\Stas\Documents\GitHub\test\project.csproj]

If i change build script like
`$msbuildExe = "c:\Program Files (x86)\MSBuild\14.0\Bin"
  Exec { & "$msbuildExe\MSBuild.exe" $solution /p:Configuration=Debug /p:VisualStudioVersion=14.0 /m}`
it works fine!

What could be problem with msbuild? I guess that msbuild is defined in some wrong way...

**Comment by stasburn** [comment]
simple run
`task ShowMsBuildVersion {
  msbuild /version
}`
gives me version number: 4.6.1055.0

**Comment by jlogar** [comment]
seems similar to #187 (i know this is an old issue, just commenting for reference here I guess if somebody stubles across this)
