### ISSUE TITLE
Release Notes for 4.6.0

### ISSUE THREAD

**Issue by chriskolenko** [psake/psake#166]
Hey just trying to find out what's new with psake 4.6.0 compared to 4.5.0.

Is there a readme with the differences? Sorry if I've missed it somewhere.

**Comment by gep13** [comment]
@chriskolenko you can find all the release information here:

https://github.com/psake/psake/releases

Hope that helps!

**Comment by gep13** [comment]
@chriskolenko were you expecting to see this information somewhere else?  If so, where?  Want to make this information as easy to find as possible.

**Comment by chriskolenko** [comment]
I looked everywhere except the most obvious place. Cheers.

Looks like 4.6.0 is worth the upgrade.
