### ISSUE TITLE
Non terminating errors

### ISSUE THREAD

**Issue by mabead** [psake/psake#167]
When I write build scripts, I typically have two kinds of errors:
- **stop right now errors**: this should stop the build right now! There is no point in going further. This typically occurs when a compilation error is found.
- **continue after error**: this kind of error should not stop the build script flow but they should be reported at the end. The typical use case for these errors is unit tests. When I run unit tests, I want my build script to continue when a test run has failed tests. My script may have other tests to run and I want all these runs to complete before saying that the build has failed.

The first kind of error is supported out of the box by psake through, Exec, Assert or simply by throwing exceptions. The problem is that the second kind of errors is not supported. There is no mechanism to flag an error but continue running the psake script.

My idea is to add a `-continueOnError` options to both `Assert` and `Exec`. When Assert or Exec fails and -continueOnError is used, execution would continue and the error would only be communicated at the end through the $psake.build_success variable.

If you agree with the proposition, I am willing to do the changes and submit a pull request.

**Comment by mabead** [comment]
@gep13 Hi Gary, what do you think about my suggestion? Would you accept a PR for this?

**Comment by mabead** [comment]
@damianh @JamesKovacs Hi Damian and James. Would you accept a PR for this?

**Comment by damianh** [comment]
Hi, I'm not actively involved in this project at this time, so... I
abstain.

**Comment by mabead** [comment]
A few years later, I guess it won't be adressed ;) 

Note that since then, I have switched to the excellent [Cake](https://cakebuild.net/) build system.
