### ISSUE TITLE
Exec has a dangerous signature

### ISSUE THREAD

**Issue by mabead** [psake/psake#168]
Let's consider the following psake script:

```
Task Foo {

    dir $env:ProgramFiles| ForEach {
        Exec {
            Write-Host "Current item is $_"
            $global:LASTEXITCODE = ($_.Name.Length % 2)

            Write-Host "LASTEXITCODE = $LASTEXITCODE"
        } -maxRetries 4
    }
}
```
When calling this psake script, what do you expect? As soon as a file that has a file name length that is not a multiple of two, Exec should retry 4 times before throwing an exception. Let's run this script:
```
PS D:\> Invoke-psake D:\psake_exec_isue.ps1 Foo
psake version 4.5.0
Copyright (c) 2010-2014 James Kovacs & Contributors

Executing Foo
Current item is 7-Zip
LASTEXITCODE = 1
Try 1 failed, retrying again in 1 second...
Current item is
LASTEXITCODE = 0
Current item is Application Verifier
LASTEXITCODE = 0...
```
The first item processed is 7-zip which has a file name length of 5. Unexpectedly, it retries only once and it does not see any error on the second attempt! Furthermore, we see that the second call to Write-Host shows an empty file name!  

Why is that? This is because the $_ variable is overwritten in the catch block of Exec. So, when the scriptblock is called for the second time, $_ does not contain the original variable anymore.

My proposition to fix this would be to add another parameter to Exec just like it is done in Start-Job: ArgumentList. The arguments would then be provided to the script block when it is called. Ex:
```
Task Foo {

    dir $env:ProgramFiles| ForEach {
        Exec {
            param($file)
            Write-Host "Current item is $file"
            $global:LASTEXITCODE = ($file.Name.Length % 2)

            Write-Host "LASTEXITCODE = $LASTEXITCODE"
        } -maxRetries 4 -ArgumentList $_
    }
}
```

**Comment by dlwyatt** [comment]
That's an option.  Another approach could be this:

```posh
Task Foo {

    dir $env:ProgramFiles| ForEach {
        $file = $_

        Exec {
            Write-Host "Current item is $file"
            $global:LASTEXITCODE = ($file.Name.Length % 2)

            Write-Host "LASTEXITCODE = $LASTEXITCODE"
        } -maxRetries 4
    }
}
```

That's a common "gotcha" in PowerShell code; it's a good practice to capture the value of $_ in another variable before moving on with the rest of your block.

**Comment by mabead** [comment]
@dlwyatt Good point and simpler! As a very edge cas, note that the problem still exists if my script block uses a variable that also exists within "Exec". Ex:

```
Task Foo {

    dir $env:ProgramFiles| ForEach {
	    $tryCount = 22  # This variable also exists in Exec
	    $x = $_
        Exec {
		    Write-Host "tryCount = $tryCount"
            Write-Host "Current item is $x"
            $global:LASTEXITCODE = ($x.Name.Length % 2)
        } -maxRetries 4
    }
}
```
This results in:
```
Executing Foo
tryCount = 1
Current item is 7-Zip
Try 1 failed, retrying again in 1 second...
tryCount = 2
Current item is 7-Zip
Try 2 failed, retrying again in 1 second...
```
We therefore see that my script block does not use the value 22 as expected.

My solution is to call GetNewClosure on the script block. This will print "tryCount = 22" as expected:

```
Task Foo {

    dir $env:ProgramFiles| ForEach {
	    $tryCount = 22  # This variable also exists in Exec
	    $x = $_
        Exec {
		    Write-Host "tryCount = $tryCount"
            Write-Host "Current item is $x"
            $global:LASTEXITCODE = ($x.Name.Length % 2)
        }.GetNewClosure() -maxRetries 4
    }
}
```

All that being said, I agree with you. This is a PowerShell behavior that should not be handled by psake. It should be handled by the psake consumer.
