### ISSUE TITLE
'how to fail a build' article is incomplete

### ISSUE THREAD

**Issue by Glober777** [psake/psake#169]
It looks like the How to fail a build article is incomplete as the version published at GitHub's wiki has much more content.

**Comment by gep13** [comment]
@Glober777 can you provide links to where you are seeing the discrepancy?

Thanks!

**Comment by Glober777** [comment]
@gep13 Sure. Here's the link that has incomplete article (new documentation location):
http://psake.readthedocs.org/en/latest/how-to-fail-a-build/

...and here's the complete one:
https://github.com/psake/psake/wiki/How-can-I-force-the-build-to-fail-if-a-command-line-program-I-run-from-a-task-fails%3F
