### ISSUE TITLE
Fix broken AppVeyor Build

### ISSUE THREAD

**Issue by gep13** [psake/psake#172]
Bottom line, it doesn't work :smile: 

https://ci.appveyor.com/project/psake/psake/build/1.0.54

The Webhook Integrations have been set up, but nothing else.

**Comment by devblackops** [comment]
In [this](https://github.com/psake/psake/tree/ci-pester-tests) branch, I've started work on getting AppVeyor and Travis executing Pester tests. Still more work needs to be done but it's a start.

**Comment by devblackops** [comment]
PR #220 is merged that gets AppVeyor/Travis correctly passing success/failed status.
