### ISSUE TITLE
Feature Request: Build in command for installing choco models

### ISSUE THREAD

**Issue by ravensorb** [psake/psake#177]
It would be great if there was build in command for installing choco models that handles checking for errors and logging correctly.

**Comment by gep13** [comment]
@ravensorb can you expand on exactly what you are looking for here?

**Comment by ravensorb** [comment]
Sorry for the delay -- the idea would be a build in way to verify chocolatey is installed and gracefully handle if it wasn't and possible a way to indicate packages that the build script depends on.

**Comment by gep13** [comment]
@ravensorb I could see this being added into the psake-contrib project as a helper function in there, but I don't think psake core would be the right place to do this.  You can see an example of where I have done this in the past:

https://github.com/chocolatey/ChocolateyGUI/blob/develop/BuildScripts/default.ps1#L76

Hope that helps!
