### ISSUE TITLE
Choose framework or build tools versions when multiple are available

### ISSUE THREAD

**Issue by Ian2020** [psake/psake#183]
For frameworks 4.5.1/2 Psake appears to include two versions of msbuild, giving priority to the most recent (14). From psake.psm1:

```
{($_ -eq '4.5.1') -or ($_ -eq '4.5.2')} {
            $versions = @('v4.0.30319')
            $buildToolsVersions = @('14.0', '12.0') <---- HERE
}
```

We'd actually like Psake to use 12.0 even if 14.0 is installed, as we are not fully ready to move to VS2015 yet but some devs may have it installed. I couldn't see a way to do this though. Have I missed something or would this be a new feature? Thanks

**Comment by taylorjonl** [comment]
This would be a new feature.

**Comment by Ian2020** [comment]
Closing this as no longer required for me, we worked around it.
