### ISSUE TITLE
Use a more discover friendly default psake file instead of default.ps1

### ISSUE THREAD

**Issue by glennsarti** [psake/psake#185]
The default psake build file of `default.ps1` is completely ambiguous without inspecting its contents.  Rake has a `Rakefile`, bundle has a `Gemfile` etc. so should psake have a `Psakefile.ps1` ?

Given that one of benefits of build automation is discoverability it would make sense that the default build file should be self-evident, or at very least suggest what it's intent is.

Assuming this is an accepted (and is a good idea) I would propose the following;
version 4.y
1. Change the default behaviour to load `default.ps1`.  If it does not exist use `psakefile.ps1`.  This would maintain backwards compatibility until a major version is released.
2. Add a deprecation warning if loading `default.ps1`.
3. Update documentation with deprecation and to say that version `4.y` prefers `psakefile.ps1`

version 5.0
1. Remove support and documentation for `default.ps1`

**Comment by glennsarti** [comment]
I would be happy to raise a PR for the 4.x series of changes.

**Comment by gep13** [comment]
@glennsarti that would be great! 👍

**Comment by glennsarti** [comment]
@gep13 PR is up for review.
