### ISSUE TITLE
EXEC{} doesn't wait until build(external Windows subsystem based EXE) is completed

### ISSUE THREAD

**Issue by kulmam92** [psake/psake#186]
I need to run below command to build SSAS project
& "C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\devenv.exe" "c:\test\test.dwproj" /build development

When I run this using EXEC{} it doesn't wait till build is completed. Because of that next script that looks for the one of the output files failed. So I had to add "Out-Null"
& "C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\devenv.exe" "c:\test\test.dwproj" /build development|Out-Null

I suggestion for this is
1. Add option to make EXEC wait until command is completed
2. Run as job and add logic to wait

Let me know if you can consider one of my suggestions or whether there's any other good alternatives.

Thank you in advance.

**Comment by jdelaney731** [comment]
works fine either way with proper syntax...exec waits on return:
Task testexec{
	"1"
	Exec{c:\windows\system32\Ping.exe "127.0.0.1"}
	"2"
	Exec{& "c:\windows\system32\Ping.exe" "127.0.0.1"}
	"3"
}

output:
Executing testexec
1

Pinging 127.0.0.1 with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
2

Pinging 127.0.0.1 with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
3

Build Succeeded!

**Comment by kulmam92** [comment]
Can you test using devenv.exe(visual studio executable)?

**Comment by jdelaney731** [comment]
Not sure about devenv, but msbuild.exe does.  Does devenv start an additional process and immediately exit?

**Comment by kulmam92** [comment]
This issue happened when I used devenv. I don't know how devenv is executing command.

**Comment by dlwyatt** [comment]
Windows apps will immediatey return when launched from the console.  Possible that devenv.exe falls into that category.  (msiexec.exe is another example.)

If that's what's happening here, use `Start-Process -Wait` to work around it:

```posh
Start-Process -FilePath "C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\devenv.exe" `
              -Wait `
              -ArgumentList "c:\test\test.dwproj", '/build', 'development'
```

**Comment by jdelaney731** [comment]
Ah, that makes sense.  I've only used console apps in my build jobs.

**Comment by kulmam92** [comment]
Would you consider making EXEC{} to support this?

**Comment by dlwyatt** [comment]
Kind of tricky.  We'd have to parse the script block passed to exec, replace calls to external commands with calls to Start-Process, hope it doesn't break anything.  Probably better to make the user responsible for their own scripts, instead of trying to rewrite their code behind the scenes.

**Comment by kulmam92** [comment]
OK. I found some good links that explains why you need to use start-process for devenv.

https://social.technet.microsoft.com/Forums/windowsserver/en-US/d1653b41-8d13-4e43-894c-b2eb7fd802f0/retrieving-msiexec-exit-code-in-powershell?forum=winserverpowershell

https://social.technet.microsoft.com/Forums/sharepoint/en-US/5b318b42-27c9-49d1-8c19-c5d7f0b9dbb2/getting-exit-code-from-startprocess?forum=winserverpowershell
