### ISSUE TITLE
Value of $config.taskNameFormat Not Written in Colour for Scriptblocks

### ISSUE THREAD

**Issue by damianpowell** [psake/psake#189]
According to the sample psake-config.ps1, I can set `$config.taskNameFormat` to a string or a scriptblock in order to control the output of task headers. While setting to a string appears to work just fine, setting to a scriptblock does not.

Outputs in colour:

```
$config.taskNameFormat = "Executing {0}"
```

Does not output in colour:

```
$config.taskNameFormat = { param($taskName) "Executing $taskName at $(get-date)" }
```

The reason for this is easy to see in the psake.psm1 (line 89):

```
if ($currentContext.config.taskNameFormat -is [ScriptBlock]) {
    & $currentContext.config.taskNameFormat $taskName
} else {
    WriteColoredOutput ($currentContext.config.taskNameFormat -f $taskName) -foregroundcolor Cyan
}
```

It's plain to see that the result of `$config.taskNameFormat` is being evaluated and left to go to the pipeline where it is being rendered as a standard string when it is defined as a scriptblock, but it is being passed to `WriteColoredOutput` in all other cases. Should the scriptblock case also pass the result to `WriteColoredOutput`? If not, then we probably need a different variable for the scriptblock case.

**Comment by damianpowell** [comment]
I submitted a pull request (#190).

**Comment by devblackops** [comment]
Thanks @damianh. Merged.
