### ISSUE TITLE
Add support for Build Tools 15 (Visual Studio 2017)

### ISSUE THREAD

**Issue by dennisdoomen** [psake/psake#201]
Unfortunately this is not so trivial since VS2017 doesn't create those registry entries anymore and keeps the build tools within its installation directory.  Instead, you're supposed to use a specific interop assembly to find the instances installed (or use [this PowerShell module](https://github.com/Microsoft/vssetup.powershell)). [Cake](https://github.com/cake-build/cake) solved this by assuming a base-directory, e.g. `C:\Program Files (x86)\Microsoft Visual Studio\2017` and then scanning within that directory for subfolders named `Professional`, `Enterprise` or `Community`. I'm willing to add this as a PR if you're interested.

**Comment by SamPosh** [comment]
I tried to call Msbuild for Visual studio 2017 with full path. When i was directly calling Msbuild.exe and compile , it compiled by excluding Unloaded projects. But when i was doing it via Psake ,it tried to build unloaded projects and show compilation issue in them. We unloaded it so that no need to build.

**Comment by SamPosh** [comment]
I am trying to call directly the MSbuild with full path for now and it works

**Comment by sala91** [comment]
Heres a simple fix

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0]
"MsBuildToolsPath"="C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\15.0\\Bin"

**Comment by mboltuc** [comment]
Another possible (but maybe not great) solution would be to implement similar to the [gulp-msbuild](https://github.com/hoffi/gulp-msbuild/blob/master/lib/msbuild-finder.js) did it.

**Comment by dennisdoomen** [comment]
Never mind. I've decided to try Cake instead.

**Comment by gep13** [comment]
>@dennisdoomen said...
Never mind. I've decided to try Cake instead.

This is pretty much where I am as well.  When I became co-maintainer of the psake project, I had every intention of actively developing/maintaining it, but since then, I have jumped in with Cake, and I haven't looked back since.  I have very much enjoyed using psake, but perhaps it is time to let someone else take over the project.  Perhaps I will open up an issue to see if anyone is interested.

**Comment by dmarlow** [comment]
I would appreciate the support in psake. I have too much to move to cake in a timely fashion.

**Comment by Kreism** [comment]
@taylorjonl did that allready, pull request is still open...
See PullRequest: https://github.com/psake/psake/pull/209
We implementet it and its working fine for us now.

**Comment by johnsonlu** [comment]
There is a tool named vswhere can help you to find the installation path of VS2017 and newer vesion.

https://github.com/Microsoft/vswhere

**Comment by dermeister0** [comment]
I use [VSSetup](https://www.powershellgallery.com/packages/VSSetup) module and a special cmdlet - [Initialize-MSBuild](https://github.com/Saritasa/PSGallery/blob/master/modules/Saritasa.Build/Saritasa.Build.psm1#L281). I call it from pre-build psake task.

**Comment by jlogar** [comment]
a side question - what other v14 tools will be used if this is only bypassed by directly invoking msbuild.exe from the correct location?

**Comment by littleKing82** [comment]
@Kreism, when you planning to release this fix? I do need of it.

**Comment by FreFre** [comment]
Thx @dermeister0 ! Works perfectly for me!

**Comment by floekke** [comment]
@dermeister0 Regarding "I use VSSetup module and a special cmdlet - Initialize-MSBuild. I call it from pre-build psake task." How do you setup psake to actually use the msbuild from path?

**Comment by tapmantwo** [comment]
@floekke looks like this line does it. https://github.com/Saritasa/PSGallery/blob/master/modules/Saritasa.Build/Saritasa.Build.psm1#L306
