### ISSUE TITLE
Exception: Unknown .NET Framework version 4.6.2

### ISSUE THREAD

**Issue by Ciwan1859** [psake/psake#202]
Hello

First of all, thank you for psake! I'm watching a PluralSight course on it and TeamCity right now.

I am facing an issue. All my projects are coded against .NET Framework 4.6.2. I have built my PowerShell psake script and in it, I have the following:

```cs
# call psake
Invoke-psake -buildFile .\default.ps1 `
              -taskList Test `
              -framework "4.6.2" `
              -properties @{
                "buildConfiguration" = "Release"
                "buildPlatform" = "Any CPU" } `
              -parameters @{ "solutionFile" = "..\BB.sln" }
```

But this throws an Exception! The exception message is:

> [<<==>>] Exception: Unknown .NET Framework version, 4.6.2 specified in 4.6.2.

Any help would be greatly appreciated!

**Comment by jozefizso** [comment]
We use `Framework "4.6"` to build our .NET Framework 4.6.2 projects.

**Comment by taylorjonl** [comment]
Support for 4.6.2 is in this pull request #209 which is currently pending.

**Comment by devblackops** [comment]
#222 added support for `4.6.2`.
