### ISSUE TITLE
psake needs a new maintainer

### ISSUE THREAD

**Issue by gep13** [psake/psake#204]
It really pains me to have to do this, after closing out this [issue](https://github.com/psake/psake/issues/130) but with other OSS and personal commitments, I simply don't have the time to work on this project.  If anyone is interested in helping to keep this project up to date, then please reach out, and I can let you know the various "things" that would be needed to push out releases, etc.

**Comment by lzybkr** [comment]
@nitroman - maybe this is a good way to take your ideas in Invoke-Build and get broader reach with the psake familiarity, hopefully in a compatible enough way.

**Comment by nightroman** [comment]
@lzybkr (did you mean **nightroman**?)

I like psake and would like it to live. But I cannot maintain it (if you are suggesting this, not completely sure). I have enough other projects to maintain, including *Invoke-Build* in the first place.

**Comment by lzybkr** [comment]
Oops, yes @nightroman - I was typing on a phone with a small font with no suggestions, oh well.

I think it's very helpful if the best PowerShell build tool is named `psake` because names matter in this case - `make`, `rake`, `fake`, `cake`, etc.  Also - many folks hear about `psake` and don't look at alternatives, assuming it's the obvious choice.

But I don't think `psake` is the best build tool for PowerShell. So I'm looking for ways to make `psake` the best build tool for PowerShell.

So what I was hoping was that you might find some way to merge `Invoke-Build` and `psake` into one project. There are multiple ways that could happen, some easier than others, but I thought it useful to start the conversation.

**Comment by nightroman** [comment]
> merge Invoke-Build and psake into one project

It would be Frankenstein, I afraid. There are significant differences, even if they are not obvious on the surface. I started *Invoke-Build* for reasons. *psake* could not be adjusted easily, I considered this option.

**Comment by cgibbons** [comment]
We've already begun the conversion of all our scripts from psake to Invoke-Build

**Comment by lzybkr** [comment]
@cgibbons - It would be great to get feedback on how that goes - e.g. if a tool could help that along, that would be good to know.

With semantic versioning, it might be reasonable if version `n+1` of psake is Invoke-Build.

**Comment by majkinetor** [comment]
Why not just put a link to invoke-build on psake readme.

**Comment by gep13** [comment]
>@majkinetor said...
Why not just put a link to invoke-build on psake readme.

That will likely happen if no-one wants to continue development on psake.  Going to leave this issue open for a little while longer, and then make a decision.

**Comment by daviwil** [comment]
I think the PowerShell team *might* be able to help keep psake going but I need to talk to a few more people before we can totally commit to that.  A goal would be to shepherd development of psake with the help of the PowerShell community.

**Comment by daviwil** [comment]
Hey @gep13, what's the best way to contact you?  E-mail?  Twitter?

**Comment by devlead** [comment]
@daviwil likely email
http://www.gep13.co.uk/contact

**Comment by daviwil** [comment]
@devlead Thanks!

**Comment by Jaykul** [comment]
Did the MS team take this, or what?

**Comment by daviwil** [comment]
Keith and I did, we just haven't made an announcement yet.

**Comment by gep13** [comment]
@daviwil let me know if there is anything else you need in order to kick start things.

**Comment by toast-gear** [comment]
@daviwil So what happened with this in the end? I can see Keith and yourself mentioned that you have taken the project over. Is this still the case? There hasn't been activity for a while.

**Comment by knunery** [comment]
@daviwil I'm also curious where this landed.

**Comment by daviwil** [comment]
Hey folks, I apologize for the silence on this.  I've been pretty overcommitted over the last few months so I haven't had much time to move things forward.  Are either of you interested in helping maintain the project?

**Comment by Jaykul** [comment]
I am.

**Comment by devblackops** [comment]
I’m interested in helping out as well.

**Comment by gep13** [comment]
>@Jaykul said...
I am. But you know I would change things...

Change is good 👍

**Comment by rkeithhill** [comment]
Changes are going to be required to get this to run better on PS Core.  There are assumptions about availability of Visual Studio versions that need to be made conditional upon the platform.

**Comment by Jaykul** [comment]
*sigh*

> assumptions about availability of Visual Studio

This project needs an identity, a statement of purpose, and a agile manifesto-style list of values...

**Comment by devblackops** [comment]
@Jaykul  I’ll bite.

For me, psake is/should:
* Be a framework to define a list of tasks (scriptblocks) and execute according to dependency rules.
* Is not a replacement for MSBuild. IMO psake should concern itself with managing task execution, not what the tasks do themselves.
* Should not have opinionated tasks built in but allow for task sharing/publication via PowerShell modules. You can be as opinionated as you want via your own task modules.
* Support some type of convention for dynamic resolution(installation) of task modules so I can write the smallest possible psake file to pull in and execute tasks from a share source.

### psake.ps1
```powershell

task Default -depends Test

task Test -depends ‘PSModuleTasks:Analyze’, ‘PSModuleTasks:Pester’, ‘MyTaskModule:Publish’

task ‘PSModuleTasks:Analyze’

task ‘PSModuleTasks:Pester’

task ‘MyTaskModule:1.0.1:Publish’
```

The example psake file above is an idea of how one might dynamically install task modules (PSModuleTasks and MyTaskModule) and execute specific tasks contained within.
This would allow for a common task module to be used by the PS community and also allow for personal/company specific modules.

**Comment by toast-gear** [comment]
For my requirements I need an automation framework rather than a replacement for msbuild. The stated goal from the root README.markdown is : 'psake is a build automation tool written in PowerShell. It avoids the angle-bracket tax associated with executable XML by leveraging the PowerShell syntax in your build scripts'. I am pretty new to psake but I would assume based on that the goal was to replace MSBuild given it's a build automation framework, written in PowerShell and it talks about replacing XML.

**Comment by devblackops** [comment]
I have offered and @gep13 has agreed that I'll be assuming maintainer duties for psake.

My first goal is to introduce an XML based DSL.....jk 😄 

Right now, I'm going to focus on the necessary project plumbing so subsequent versions can be released quickly and taking a look at pending PRs and issues to see what can be merged/closed out.

**Comment by rkeithhill** [comment]
Awesome.  The main PR I want to see get merged **after** some tweaking is the PR for VS 2017 support - #219.

**Comment by devblackops** [comment]
@rkeithhill Are you planning to update #219?

**Comment by rkeithhill** [comment]
I can do that but I probably won't be able to get to it until tomorrow night.  But I should be able to finish it in a night.
