### ISSUE TITLE
Plugin for autodetection of psake tasks in VS-Code

### ISSUE THREAD

**Issue by sriprasannaMG** [psake/psake#210]
Hi,
It was nice to see the integration of grunt in VS-Code by means of auto-detection. 
Is there any plan for a psake-vscode-plugin for integration of psake tasks into VS-code?
Refer: https://code.visualstudio.com/docs/editor/tasks#_autodetecting-gulp-grunt-and-jake-tasks

**Comment by eweilnau** [comment]
There is already a VS Code plugin for psake here https://github.com/psake/psake-vscode. It currently only provides snippets.

**Comment by gep13** [comment]
@eweilnau yes, it is a *very* basic addin, but it could certainly be expanded.

**Comment by gep13** [comment]
@devblackops I have recently went through this process for Cake (finding Tasks based on the presence of a build.cake file).  Now that we are standardising on a specific name for the psake file, the VSCode extension could easily be updated to look for the presence of this file, and if it finds it, list out all of the available tasks, and then execute the specified one.

**Comment by rkeithhill** [comment]
Which VSCode extension?  AFAIK psake has no VSCode ext other than one for snippets.  Or are you talking about the PowerShell extension for VSCode?  Or are you talking about creating a psake extension?  Maybe spin up a `psake\VSCode` project?

**Comment by rkeithhill** [comment]
OK, just saw the reference to the snippets code extension.  Yes, that could be extended to add task auto-detection and a built-in `$psake` problem matcher.

**Comment by devblackops** [comment]
@gep13 That would be awesome!

**Comment by gep13** [comment]
@devblackops @rkeithhill let me see if I can carve out some time to do this 😄

**Comment by gep13** [comment]
I am going to go ahead and close this issue, as it will now be tracked over here: https://github.com/psake/psake-vscode/issues/3
