### ISSUE TITLE
Support for ASP.NET core project

### ISSUE THREAD

**Issue by henryhe9999** [psake/psake#214]
Does psake have support for ASP.NET core project? If so, how to configure it?

**Comment by raghav710** [comment]
@henryhe9999 similar to what we do in normal ASP.NET projects, you just need to define the tasks in your build script that are capable of compiling, packaging etc. your code and use psake to execute those tasks

**Comment by henryhe9999** [comment]
@raghav710 Thank you for the quick response :-D
