### ISSUE TITLE
Bug Fix release

### ISSUE THREAD

**Issue by PowerSchill** [psake/psake#217]
Any chance we could get a bug-fix release with the latest changes in order to get a PS core functioning version in the PSGallery?

**Comment by rkeithhill** [comment]
@PowerSchill I must be blind but I'm not seeing the build/test results from your latest PR https://github.com/psake/psake/pull/216.  Have you had a chance to test on Linux and/or macOS?  

FWIW I don't have the ability to push a release to the gallery.  @daviwil Can you push a release?

**Comment by PowerSchill** [comment]
I deleted the branch 3 days ago but you can see my successful build at https://travis-ci.org/PowerSchill/psake/builds/252542285 for that branch. I actually had to manually install this build so I can use my Plaster templates. Haven't had any issues with it since.

**Comment by gep13** [comment]
>@rkeithhill said...
FWIW I don't have the ability to push a release to the gallery.

@daviwil is it possible to again use the psake-bot account as the main account to push to the gallery?  That again will allow everyone on the team who is helping to push out new versions.

**Comment by PowerSchill** [comment]
Any chance we can get an update?

**Comment by devblackops** [comment]
@PowerSchill Once #228 is pulled in, I think we're ready for a `v4.7.0` release.

**Comment by devblackops** [comment]
@PowerSchill `v4.7.0` released to PSGallery, Chocolatey (awaiting review), and nuget.org.

https://www.powershellgallery.com/packages/psake/4.7.0
