### ISSUE TITLE
Prep for 4.7.0 release

### ISSUE THREAD

**Issue by rkeithhill** [psake/psake#225]
* Update PSD1 to 4.7.0 and copyright to 2017.
* Update CHANGELOG.md with all changes.
* Should we consider dropping PS 2.0 now that it is deprecated?  There is a #requires -version 2.0 in psake.psm1 file and the PowerShellVersion field in the psd1 file.

**Comment by devblackops** [comment]
It is probably safe to support PowerShell 3+.

I would also like to flesh out the help documentation for the public functions.

We should also consider @glennsarti's PR #185 to deprecate `default.ps1` in favor of `psakefile.ps1`. What do you think?

**Comment by rkeithhill** [comment]
RE #185 - agreed.

**Comment by devblackops** [comment]
@rkeithhill Once #228 is merged in, I think we're ready for `v4.7.0`. Mind cloning down that PR and giving it a once over? If it looks good. I'll merge it in and push `v4.7.0` to the gallery.

**Comment by rkeithhill** [comment]
OK if I do that tonight?

**Comment by devblackops** [comment]
No problem. It's a big PR so take your time.
