### ISSUE TITLE
xcode tag set on Ubuntu Travis CI jobs

### ISSUE THREAD

**Issue by tlindsay42** [psake/psake#231]
The xcode tag is set on Ubuntu Travis CI jobs due to how the matrix is configured.  I ran into the same issue on my Armor PowerShell Module project last month while I was figuring this out.

## Expected Behavior

The xcode tag should not be set for Ubuntu Trusty Travis CI jobs.

## Current Behavior

The xcode tag is set for Ubuntu Trusty Travis CI jobs.  Example: https://travis-ci.org/psake/psake/builds/305600748

## Possible Solution

Minor update to the .travis.yml file to be more explicit in the matrix.

## Context
Job tagging can be improved to help prevent end user confusion.

## Your Environment
* Module version used: N/A
* Operating System and PowerShell version: N/A

**Comment by devblackops** [comment]
Fixed in #232. Thanks @tlindsay42!
