### ISSUE TITLE
Cannot find a variable with the name 'IsWindows'.

### ISSUE THREAD

**Issue by Craigfis** [psake/psake#234]
## Expected Behavior
Existing scripts that were working before V4.7 should continue to work. 

## Current Behavior
With this 4.7 release our scripts now fail due to psake expecting an IsWindows variable to be defined.

## Possible Solution
Provide a default value for IsWindows? Remove the use of that variable?

## Steps to Reproduce (for bugs)
Not yet sure what action in our scripts is triggering this behavior.

## Context
Our existing project build scripts have suddenly started failing.

## Your Environment
Running on Windows (10).
* Module version used: 4.7
* Operating System and PowerShell version:

**Comment by rkeithhill** [comment]
Are you using `Set-StrictMode -Version`?  Usually PowerShell doesn't care if a variable exists or not unless you are in strict mode.  That said, this is easily fixable.  We can't remove the use of the variable since there are places we need to ensure we are on Windows as opposed to Linux/macOS.  But we can conditionally (if it exists) access that variable's value.

**Comment by Craigfis** [comment]
No, we're not using Set-StrictMode.

**Comment by rkeithhill** [comment]
The only spot where I see we use $IsWindows is guarded:
```
    if (!(Get-Variable -Name IsWindows -ErrorAction SilentlyContinue) -or $IsWindows) {
```
If the `Get-Variable` call fails (silently) then we assume this is not PS Core but regular ol' PowerShell which is Windows only.  Now this will generate a non-terminating error record but it is not an error.

Can you repro the error and paste in the output of the command `$error[0] | fl * -force`?  You might have to look through the errors in $error to find the index that corresponds to the IsWindows not found error.

**Comment by rkeithhill** [comment]
Also, can you find the psake module install location,  open up private\ConfigureBuildEnvironment.ps1 and replace line 3 with this:
```posh
    if (!(Test-Path Variable:\IsWindows) -or $IsWindows) {
```
See if that behaves any better.

**Comment by Craigfis** [comment]
On this if condition, if the first clause returns false then it will go ahead and attempt to evaluate the second:
if (!(Get-Variable -Name IsWindows -ErrorAction SilentlyContinue) -or $IsWindows) 

Shouldn't that be:
if ((Get-Variable -Name IsWindows -ErrorAction SilentlyContinue) -and $IsWindows) 
?

**Comment by rkeithhill** [comment]
If `IsWindows` doesn't exist as a variable then yeah, get-variable will return $null but the `!` will invert that to $true which should short-circuit the `$IsWindows` check.

**Comment by rkeithhill** [comment]
The `Test-Path` approach is better anyway since it won't generate an error record if the variable doesn't exist.

**Comment by Craigfis** [comment]
Yep, sounds like that is the problem. The end of our script reports all the error records.

**Comment by rkeithhill** [comment]
OK, well then the next drop (4.7.1 probably) will have this change.  Hopefully that line change gets you by for now?

**Comment by devblackops** [comment]
@rkeithhill That will also give us a chance to fix validation issue with the Chocolatey package.

**Comment by Craigfis** [comment]
Thanks. I've worked around it for now by setting IsWindows to true in our script.
