### ISSUE TITLE
Can't run build.ps1 in WSL

### ISSUE THREAD

**Issue by rkeithhill** [psake/psake#237]
I often want to test psake in Ubuntu in my WSL console.  But running build.ps1 generates errors:

## Expected Behavior

The commands should be made to work on Linux. In fact, doesn't one of the nightly builds build on Linux?  

## Current Behavior

PS /mnt/c/Users/Keith/GitHub/psake/psake> ./build.ps1 -Task Pester
Invoking Step: Init
Check-PSGalleryApiAvailability : Exception calling "GetIsNetworkAvailable" with "0" argument(s): "An error was encountered while querying information from the operating system."
At /opt/microsoft/powershell/6.0.0-rc/Modules/PowerShellGet/1.5.0.0/PSModule.psm1:6329 char:17
+ ...     $null = Check-PSGalleryApiAvailability -PSGalleryV2ApiUri $Script ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Check-PSGalleryApiAvailability], MethodInvocationException
+ FullyQualifiedErrorId : NetworkInformationException,Check-PSGalleryApiAvailability

## Steps to Reproduce (for bugs)

1. Open up WSL
2. Install latest PowerShell Core by following these instructions [here](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1604)
3. Cd to your Windows Git repo using the location `/mnt/c/<windows-path>`
4. Start powershell with `pwsh`
5. Run `./build.ps1 -Task Pester`

## Your Environment

* Module version used:
* Operating System and PowerShell version:

**Comment by devblackops** [comment]
This seems to be a bug in PowerShellGet.

Specifically, `Get-PSRepository` works in WSL. `Get-PSRepository -Name PSGallery` does not. 😕 

If we change it to `$psGallery = Get-PSRepository | Where-Object {$_.Name -eq 'PSGallery'}` we get past the first issue but then `Set-PSRepository -Name PSGallery -InstallationPolicy Trusted -Verbose:$false` fails with:

```powershell
Exception calling "GetIsNetworkAvailable" with "0" argument(s): "An error was encountered while querying information from the operating system."
At /opt/microsoft/powershell/6.0.0-rc/Modules/PowerShellGet/1.5.0.0/PSModule.psm1:6264 char:9
+         $connected = [System.Net.NetworkInformation.NetworkInterface] ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : NetworkInformationException
```

**Comment by rkeithhill** [comment]
You wanna file a bug here - https://github.com/powershell/powershellget/issues

**Comment by devblackops** [comment]
Yep. Doing that now.

**Comment by devblackops** [comment]
Issue created. https://github.com/PowerShell/PowerShellGet/issues/197

**Comment by rkeithhill** [comment]
Thanks!

**Comment by devblackops** [comment]
No longer an issue with newer versions of PowerShellGet.

See: https://github.com/PowerShell/PowerShellGet/issues/197#issuecomment-491563746
