### ISSUE TITLE
Consider changing message "Build succeeded!" to "Task succeeded"

### ISSUE THREAD

**Issue by rkeithhill** [psake/psake#239]
It is not unusual for psake to do stuff that isn't related to "building something".  For instances, running a test task or an analyze task.  Seeing "Build succeeded!" doesn't seem right for the result of these tasks.  Maybe something a bit more generic like "Task succeeded!" would be better.

**Comment by devblackops** [comment]
I agree @rkeithhill

**Comment by mattmcnabb** [comment]
+1!

When you're running an actual CI build, it's confusing to see a message from psake that states that the build succeeded, especially when your build actually failed. I'd go one further and suggest that we need to add the word "psake" to the messages so you know the source in a build log.

Here's a screenshot of a failed build in Appveyor, with the "Build succeeded" message right in the middle:

![image](https://user-images.githubusercontent.com/6998507/34110180-e29a33d6-e3d3-11e7-8419-df253c12b45a.png)

**Comment by devblackops** [comment]
@mattmcnabb psake is not picking up the failure from Pester. Try the following psake task and observe the difference between commenting and uncommenting the throw statement when Pester failures are `-gt 0`

```powershell
task Pester {
    $tests = "$PSScriptRoot/Tests"
    $testResults = Invoke-Pester -Path $tests -PassThru
    if ($testResults.FailedCount -gt 0) {
        throw "$($testResults.FailedCount) tests failed!"
    }
}
```

**Comment by mattmcnabb** [comment]
Gotcha! That makes sense. My suggestion was more around adding "Psake" to any output messages to make sure we know the source of the message.

**Comment by devblackops** [comment]
I personally would like to change the output formatting of psake error messages. The following style has always bugged me a little.

```powershell
Error: 12/19/2017 9:39:06 PM:
 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: 1 tests failed!
```

**Comment by rkeithhill** [comment]
RE the success message, what do folks think about this:
![image](https://user-images.githubusercontent.com/5177512/34397007-180a2348-eb2f-11e7-8faa-f3e5c638eca9.png)

This goes a bit more generic by replacing `Build` (even `Task`) with `psake`.  I'm not sure about the `invoking 'path'.` bit.  Or maybe that should say `processing` or `executing` instead of `invoking`.   I "think" I like seeing the path to the psake file that was processed but could be convinced otherwise.

@devblackops Agree 100%. The error format needs to be improved particularly to allow us to create a VSCode psake problem matcher regex.  But could you file that suggestion in a separate issue?

**Comment by rkeithhill** [comment]
For comparison to the above:
![image](https://user-images.githubusercontent.com/5177512/34397138-86691a1e-eb30-11e7-8951-d6275281b8bf.png)

and

![image](https://user-images.githubusercontent.com/5177512/34397160-b7838a58-eb30-11e7-85ff-c05844b7c8b8.png)

**Comment by devblackops** [comment]
@rkeithhill I like `psake succeeded executing .\calling_invoke-task_should_pass.ps1`. That matches with `Executing A, B`, etc. and is similar to how Pester calls out the script being run.
