### ISSUE TITLE
Remove me as chocolatey maintainer

### ISSUE THREAD

**Issue by damianh** [psake/psake#240]
Hi, 

delighted to new life being breathed into this project. Since I'm no longer assisting, could someone remove me from the chocolately package maintainer list? TY.  @gep13 @devblackops @dlwyatt 

https://chocolatey.org/packages/psake/4.7.0/ManagePackageOwners

![image](https://user-images.githubusercontent.com/57436/33423199-71f22086-d5b8-11e7-8aa9-af2c161fb1e2.png)

**Comment by gep13** [comment]
@damianh done :+1:

**Comment by damianh** [comment]
Thanks @gep13 :)
