### ISSUE TITLE
just FYI have you seen Psakify?

### ISSUE THREAD

**Issue by Jaykul** [psake/psake#242]
Just wanted to make sure you'd seen this, given conversations about including a set of tasks 

https://github.com/SeatwaveOpenSource/psakify

**Comment by devblackops** [comment]
Nope. Haven't seen this. Thanks @Jaykul!

**Comment by HeyItsGilbert** [comment]
Doesn't seem to exist anymore.

**Comment by Jaykul** [comment]
It's called [PowerTasks](https://github.com/shaynevanasperen/PowerTasks) now...
