### ISSUE TITLE
psake-config.ps1 doesn't work

### ISSUE THREAD

**Issue by GreatTeacherBasshead** [psake/psake#246]
1. **$config.taskNameFormat = "-------- {0} --------"** in **.\psake\psake-config.ps1**
2. Import-Module .\psake\psake.psm1
3. Invoke-psake .\test.ps1

**test.ps1** looks like this:
Task Default -Depends test
Task test {
    "test"
}

## Expected Behavior
I should see the changed output format of a task name: **-------- test --------**

## Current Behavior
I see the default one: **Executing test**

## Context
I want to setup general properties and behaviors (like taskNameFormat, framework, etc.) for all psake scripts in one place. Seems it should be **psake-config.ps1**. I don't want to pass them each time as parameters or duplicate the in each script.

## Your Environment
* Module version used: 4.7.0
* Operating System and PowerShell version: Windows 10, Powershell 5.1

**Comment by devblackops** [comment]
@GreatTeacherBasshead This works fine when `psake-config.ps1` is in the same directory as your current build script. However, #228 appears to have broken loading the default `psake-config.ps1` from the module when a config file in the same directory as the build script is absent.

On it.
