### ISSUE TITLE
Shared psake tasks distributed in PowerShell modules

### ISSUE THREAD

**Issue by devblackops** [psake/psake#248]
I think it would be beneficial to support loading/executing psake tasks from modules. These task modules could then be distributed on the PSGallery and the like. Individual projects could reference the appropriate task from a common psake task module. I envision this module would include common tasks like:

- **Analyze** - Run PSScriptAnalyzer
- **Test** - Run Pester tests
- **Publish** - Publish module to PSGallery

This would encourage community-maintained psake tasks, reduce redundant code in projects, and help standardize PowerShell module layout as the psake tasks will expect a certain structure. If needed, there could be seperate tasks that tailer to various "flavors" of module layout.

## Expected Behavior
psake should be able to execute tasks contained in PowerShell modules with a simple syntax like:

```powershell
task default -depends Test

task Analyze -FromModule PowerShellBuild.Common

task Test -FromModule PowerShellBuild.Common

task Publish -FromModule MyBuildModule -Version 1.0.0
```

## Current Behavior
psake itself can be [nested inside psake tasks](https://github.com/psake/psake/wiki/Can-I-run-a-nested-build%3F) but there is no support for easily sharing common build tasks.

**Comment by Jaykul** [comment]
I'm a little confused about what the goal is here. 

PowerShell can inherently can call Functions and Cmdlets from modules ... what's different about "tasks"?

Don't you think that the goal of "community maintained psake tasks" would be better served by shipping those function **in PSake** ?

**Comment by nightroman** [comment]
Or as a separate module with typical PowerShell projects build and test oriented commands.
Then:

- psake can use it
- Invoke-Build can use it
- people who prefer their own build scripts (many) can use it

I think ideally build tasks should not implement tools, they are for assembling tools.

**Comment by devblackops** [comment]
I would prefer to keep the set of PowerShell build functions/tasks out of psake proper. I use psake for more than just PowerShell and want a mechanism to publish/version those tasks so my projects can reference and install them with the minimum amount of boilerplate like I mentioned [here](https://github.com/psake/psake/issues/204#issuecomment-338873298). I imagine this shared task module would have a greater update frequency and like @nightroman said, it should be consumable by [Invoke-Build](https://github.com/nightroman/Invoke-Build) and others as well.

I created a [PowerShellBuild.Common](https://github.com/psake/PowerShellBuild.Common) yesterday with the goal of creating common build functions (build/analyze/test/publish, etc). There is a `psakeFile.ps1` at the root of this module that will call these common functions. The shared task mechanism in [this](https://github.com/psake/psake/tree/shared-module-tasks) branch of psake has the feature to load this module and execute the tasks contained in `psakeFile.ps1`. Invoke-Build could have a similar file in the module and we would all be using the same common functions underneath.

My intent was to take much of the logic in the Plaster psake file [here](https://github.com/powershell/plaster/blob/master/build.psake.ps1) and put it in normal PowerShell functions, then create slim psake tasks in `psakeFile.ps1`.

Hope that makes sense.

**Comment by rkeithhill** [comment]
David had set up the github.com/powershell/PlasterBuild repo for such a thing but honestly after the previous summit I kind of lost energy on it.  It seemed like nobody wanted to use anybody else's stuff.  :-)  Anyway, we could resurrect the effort there (or not).  I'd be happy to add some more contributors (assuming I have perms to do so). 

My original goal is similar to what you state @devblackops.  I'd like a module of reusable functions both by psake and InvokeBuild. Then I'd like both a psake recipe script and an InvokeBuild recipe script.  The idea is that you'd dot source the recipe script and for the most part, you just tweak the build with properties and tasks that hook into various places in the build process.  This would be similar to how the C# team provides that CSharp.targets file that is built on MSBuild.  For the most part when you customize a C# project, you're tweaking MSBuild properties but if you want to customize deeper, you can hook various Targets.

**Comment by rkeithhill** [comment]
BTW, the PowerShellGet team doesn't really want us publishing the output of **every** build to the PSGallery.  :-)  The publish task might be better left as a "manual" step unless you're publishing to your own repo.

**Comment by devblackops** [comment]
I think we're thinking along the same lines @rkeithhill. One change I made in the [shared-module-tasks](https://github.com/psake/psake/tree/shared-module-tasks) branch is Properties are stored in a stack instead of an array. This is so a common task module could define its behavior via Properties but the calling psake script would have an opportunity to declare their own version of those properties and change the behavior.

**Comment by rkeithhill** [comment]
BTW two benefits of doing this work in the PlasterBuild repo is that A) it won't appear too aligned with psake and B) we'd have a better chance of shipping with the PowerShell extension for VSCode.  I'd want to have a Plaster template def for at least script modules where you'd pick your build system `psake` or `InvokeBuild` and it would put in the appropriate recipe/script file.

**Comment by devblackops** [comment]
I don't have a problem with that. I created the other one because I wasn't aware of something already out there 😄

**Comment by rkeithhill** [comment]
OK I sent a request to @joeyaiello to get you added as a contributor to the repo.

**Comment by nightroman** [comment]
Here is some conceptual sample with imported tasks, see EXAMPLE 2:
https://github.com/nightroman/Invoke-Build/tree/master/Tasks/Import

Some users engaged this technique and provided positive feedback.

It's for Invoke-Build but the idea should work for psake, too. And it's about
"recipes" as @rkeithhill calls them. The point of interest is that it is not
based on conventional names of recipe scripts. Instead, a module explicitly
exports aliases for such recipes. A consumer calls the aliases in order to
import provided module recipe scripts.

**Comment by devblackops** [comment]
@rkeithhill @nightroman  I'm finally getting back to this idea.

I wanted to finish my thought process in the [psake/PowerShellBuild.Common](https://github.com/psake/PowerShellBuild.Common) repo without messing with PlasterBuild but I **did** borrow much of the common build code and extracted it into normal functions. What is left in `psakeFile.ps1` is just calling the functions. I imagine IB could do the same and we'd have a `IB.tasks.ps1`  file or something similar alongside `psakeFile.ps1`.

Let me know your thoughts.

**Comment by nightroman** [comment]
Invoke-Build already offers some mechanism of exported module tasks:
https://github.com/nightroman/Invoke-Build/tree/master/Tasks/Import

So changes in the IB core are not needed for this, as such. Maybe some syntax
sugar would be useful. But I am not sure yet, I would like to see more cases
and know what users want and think.

Unless I miss something, it is about discovery of an extra build file provided
by a module and importing it. In Invoke-Build simple dot-sourcing of this file
does the trick. This is not ideal, e.g. task names must be unique but it works.

New psake mechanism does not solve the issue with conflicting task names. E.g.
if the main script has `Init` and the script provided by a module has it too
then the build fails "Assert: Task init has already been defined." So this
mechanism does not add much to the usual import of extra build scripts.

Thus, why not just import scripts as usual? Like IB already shows, a module
may offer an alias for the dedicated script. Or it may be a function, etc.
The consumer script imports the exported script and uses its tasks. Simple.

P.S. I am sorry for kind of "not encouraging" the development.

**Comment by devblackops** [comment]
Yes, directly dot sourcing task files or dot sourcing via aliases that point to the task files currently works in both IB **and** psake, although I'm not positive it covers **ALL** scenarios (dependencies on tasks in other modules, overriding values in psake `Properties` function, etc). I have to do more testing on that.

The intent of all this to provide a first class mechanism within the build tool to consume tasks distributed in other modules which I don't think simple dot sourcing can fully address. You mentioned duplicate tasks, that is something that I'd like to handle (it is not currently), and there may be other issues with that I haven't uncovered yet.

If IB would prefer to use the alias method,  then that could be supported in [psake/PowerShellBuild.Common](https://github.com/psake/PowerShellBuild.Common). Thin task wrappers to the underlying functions in the module like the `psakeFIle` implements would just have to be implemented.

And ultimately PowerShellBuild.Common should probably be hosted in the [PowerShell](https://github.com/powershell) GitHub org, or get rolled back into PlasterBuild, or some other community module not directly associated with psake or IB but that both build tools can utilize.

**Comment by PeterMTaylor** [comment]
Is there a simple way that I can ask psake (for consistency) to ensure ALL classes are loaded into memory BEFORE pester runs in the test build section?

**Comment by devblackops** [comment]
@PeterMTaylor Are you referring to PowerShell classes and you have them in separate files from the `psm1`? psake doesn't offer that functionally natively, you'll have to code that up yourself in your build process. AFAIK there isn't a 100% effective and foolproof way to do this. Simply appending the contents of PowerShell class files to the `psm1` during the build process won't always work because with classes, the order matters if the classes have any dependencies on each other. Some people name the class files `00_class1.ps1`, `10_class2.ps1`, etc. to force the build order but that is brittle.

My [compile](https://github.com/poshbotio/PoshBot/blob/master/psake.ps1#L137) task in [PoshBot](https://github.com/poshbotio/PoshBot) skirts around this with a rather inelegant solution of manually defining the order.

**Comment by PeterMTaylor** [comment]
Thanks for the options...I’ll post back how I go with these variations.
