### ISSUE TITLE
Importing VSSetup module causes failure

### ISSUE THREAD

**Issue by gopi17** [psake/psake#255]
When trying to import the VSSetup module more than once in the same session, Powershell throws an error. This is being called in the ConfigureBuildEnvironment.ps1 script.

## Expected Behavior
The module should be imported 

## Current Behavior
When running Import-Module for a second time, the following error occurs:
![image](https://user-images.githubusercontent.com/22067982/42249411-f06b0204-7edf-11e8-8937-b2410956ba0b.png)

## Possible Solution
On line 99 of ConfigureBuildEnvironment.ps1, replace `Import-Module VSSetup` with `Import-Module VSSetup -NoClobber` or `Import-Module VSSetup -NoClobber -Verbose`

## Steps to Reproduce (for bugs)
1. In and Administrator Powershell window, run `Install-Module -Name VSSetup`
2. Run `Import-Module -Name VSSetup`
3. Run `Import-Module -Name VSSetup`

## Context
Due to this issue, we were not able to build our project using Psake and VS 2017. The issue was not present with Psake and VS 2015.

## Your Environment
* Module version used: VSSetup 2.2.0
* Operating System and PowerShell version: 

Windows 10 Pro v1803 build 17134.112
PSVersion 5.1 build 10.0

**Comment by devblackops** [comment]
@gopi17 Looks like this should have fixed in #249.

`master` is currently as `v4.7.1` with this change merged but that hasn't been published to the PowerShell Gallery or nuget.org yet. I'll fix that 😄

**Comment by devblackops** [comment]
@gopi17 `v4.7.1` has been published to the PSGallery. Please let us know if it's working for you.

**Comment by gopi17** [comment]
@devblackops it appears to be working. I will test again once the nuget package is up

**Comment by gopi17** [comment]
@devblackops still waiting on 4.7.1 in Nuget. Any updates?

**Comment by devblackops** [comment]
@gopi17 Sorry I dropped the ball on that. Just released to nuget.org and chocolatey.org. You should see it within the hour.
