### ISSUE TITLE
Add support for .net 4.7.2

### ISSUE THREAD

**Issue by dawoodmm** [psake/psake#256]
## Expected Behavior
.net 4.7.2 is out, and would like to have psake support builds with the same

## Current Behavior
currently there is support for upto .net 4.7.1

## Possible Solution
PR attached.
added 4.7.1 to list of supported frameworks, with msbuild 15.0

## Context
We currently use psake for build scripting, and are looking to upgrade to .net 4.7.2
however, we only can upgrade to .net 4.7.1

## Your Environment
* Module version used:
* Operating System and PowerShell version:

**Comment by StasPerekrestov** [comment]
Could you also release a new version please. https://www.powershellgallery.com/packages/psake/

**Comment by devblackops** [comment]
published. https://www.powershellgallery.com/packages/psake/4.7.2

**Comment by StasPerekrestov** [comment]
It looks like the fix hasn't been published yet. The new version is shipped, however it doesn't contain the fix.

**Comment by devblackops** [comment]
OK that's weird. The PR was merged to master but I'm not seeing the changes and commits to that file don't reflect the change. https://github.com/psake/psake/commits/master/src/private/ConfigureBuildEnvironment.ps1

**Comment by devblackops** [comment]
Whelp. Messed that up.

![image](https://user-images.githubusercontent.com/12634452/43967893-7778ecc2-9c7a-11e8-9217-85a7b8356949.png)

**Comment by dawoodmm** [comment]
right this looks good from my end. 
gonna close this out

**Comment by StasPerekrestov** [comment]
Thanks a lot!
