### ISSUE TITLE
Shared Module Tasks Version Check Too Strict

### ISSUE THREAD

**Issue by RandomNoun7** [psake/psake#268]
When Task.ps1 is determining whether the $FromModule is suitable, it does a check of the $taskModule version against $version which was passed into the file as a parameter. 

This version is strict enough that patch release differences in the version number cause the $taskModule to be rejected and the task errors out.

## Expected Behavior
My expectation would be that a patch (z) should probably not cause a module to be rejected. This is a personal assumption, but given that I don't actually know yet where the $version parameter is coming from, I can't say with certainty that this should be the expectation for all users.

## Current Behavior
The task I am executing, build, is expecting version 0.1.0 of the PowerShellBuild module. Currently I have version 0.1.1 installed. That z release difference in version number is causing the build task to fail.

## Possible Solution
Change to a version check that ensures only that Major and Minor version match. I think you could make an argument that it should be Major is equal and Minor is Greater Than or Equal, but since I don't know where the $version  parameter is actually coming from, it's hard for me to say.

## Steps to Reproduce (for bugs)
1. Install psake 4.8
2. Install PowerShellBuild 0.1.1
3. Create a module using the Stucco Module
5. Execute build.ps1 -task build

## Context
Currently I am unable to build a module with the latest version of the PowerShellBuild module unless I modify my copy of the Psake to allow the z release copy of PowerShellBuild.

## Your Environment
Psake 4.8.0
PowerShellBuild 0.1.1
0.1.0
Windows 10
PowerShell 6.1.0

**Comment by devblackops** [comment]
@RandomNoun7 What about if we add `-MinimumVersion` and `-MaximumVersion` parameters? This would allow it to work similar to `Install-Module` and `Import-Module` and would behave how most users expect. We could also rename `-Version` to `-RequiredVersion` and add `-Version` as an alias to it.

This would allow the following to work in your case:

```powershell
task Build -FromModule PowerShellBuild -MinimumVersion 0.1.0
```

**Comment by RandomNoun7** [comment]
Yeah that would be great. I see you self assigned this but if your busy with other stuff I can have PR updated with this tomorrow. I’m a little slow but I see where this param is coming from now so I can have the change and the Pester for it added in fairly short order.

**Comment by RandomNoun7** [comment]
@devblackops Also just occurred to me that I could implement something like -LessThanVersion so that you can use -MinimumVersion 1.0.0 -LessThanVersion 2.0.0 and anything in the 1 series would be accepted. Specifying that without a LessThanVersion param gets awkward.

**Comment by devblackops** [comment]
Sounds good to me. Go for it!
