### ISSUE TITLE
psake does not fail

### ISSUE THREAD

**Issue by apobekiaris** [psake/psake#270]
## Expected Behavior
It should terminate execution

## Current Behavior
Errors are hidden and executtion continues

## Possible Solution
use this syntax
```ps1
task UpdateProjects {
    Exec {
        powershell.exe .\tools\build\UpdateProjects.ps1 
        if ($lastexitcode){
            throw $errors
        }
    }
}
```
## Steps to Reproduce (for bugs)
replace powershell with `&`
```ps1
task UpdateProjects {
    Exec {
        & .\tools\build\UpdateProjects.ps1 
        if ($lastexitcode){
            throw $errors
        }
    }
}
```

## Context
I need to run scripts (ps1) from my tasks and stop when they fail.

## Your Environment
* Module version used:latest
* Operating System and PowerShell all latest

**Comment by devblackops** [comment]
@apobekiaris In your `UpdateProjects.ps1`, are you producing terminating or non-terminating errors?

**Comment by apobekiaris** [comment]
I have `$ErrorActionPreference = "Stop"` on top of the file

**Comment by devblackops** [comment]
Sorry I'm not able to repro. In my test below, `powershell.exe` is returning an exit code of `1` (which it should) since `$ErrorActionPreference = 'Stop'` is there.

Is there a specific reason you need to run a separate PowerShell process?

##### test.ps1
```powershell
$ErrorActionPreference = 'Stop'
Write-Error 'oops'
```

##### psakeFile.ps1

```powershell

task default -depends task3

task task1 {
    'task 1'
}

task task2 -depends task1 {
    exec {
        powershell .\test.ps1
    }
}

task task3 -depends task2 {
    'task 3'
}
```

##### results

```powershell
C:\temp
I ❤ PS>Invoke-psake -buildFile .\psakeFile.ps1
psake version 4.7.4
Copyright (c) 2010-2017 James Kovacs & Contributors

Executing task1
task 1
Executing task2


C:\temp\test.ps1 : oops
At line:1 char:1
+ .\test.ps1
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,test.ps1


Error: 12/19/2018 9:18:30 AM:
    .   powershell .\test.ps1~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Exec: Error executing command

C:\temp
I ❤ PS>
```

**Comment by apobekiaris** [comment]
no my requirement is to run a ps1 file from a task and if ps1 fails tto stop. How u recommend to go? I will research furtther based on your recomendattions thnsk

**Comment by devblackops** [comment]
You could simplify by removing `exec` as it is intended to detect errors in command line programs by checking the exit code. If all you are doing is running another PowerShell script, you should be able to just use `&` and ensure your script stops on errors.

```powershell
task task2 -depends task1 {
    & .\test.ps1
}
```
