### ISSUE TITLE
If parameters initialization failed, psake does not show which parameter caused a failure.

### ISSUE THREAD

**Issue by GreatTeacherBasshead** [psake/psake#271]
## Expected Behavior

If parameters initialization failed, show which parameter caused a failure.
```
Parameter 'skipBuild' is null
Error: 20/12/2018 11:09:29: 
At E:\builds\psake\public\Invoke-psake.ps1:272 char:25
 + ...             new-item -path "variable:\$key" -value $parameters.$key - ...
 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Cannot process argument because the value of argument "value" is null. Change the value of argument "value" to a non-null value.
```

## Current Behavior

If parameters initialization failed, psake does not show which parameter caused a failure.
```
Error: 20/12/2018 10:06:05: 
At E:\builds\psake\public\Invoke-psake.ps1:270 char:21
 + ...             new-item -path "variable:\$key" -value $parameters.$key - ...
 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Cannot process argument because the value of argument "value" is null. Change the value of argument "value" to a non-null value.
```

## Possible Solution

Add `try/catch` block around parameters initialization loop. Show a bad parameter in `catch` block

## Context

When there are lots of parameters, which a build server passes to psake, and one does not exist, it's always time consuming and annoying to investigate, which one is missing.

## Your Environment

* Module version used: 4.7.4
* Operating System: Windows Server 2016
* PowerShell version: 5.1

**Comment by devblackops** [comment]
Thanks @GreatTeacherBasshead. This makes sense to me.
