### ISSUE TITLE
4.8.0 - Wrong path determined for MSBuild in VS 2019 environment

### ISSUE THREAD

**Issue by dkorzhin** [psake/psake#278]
While setting up Framework to 4.5.1 the path to MSBuild is calculated as:
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin" 

## Expected Behavior
But in case of VS 2019 it should be:
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin" 

## Current Behavior

It works in case of Visual Studio 2017 since the MSBuild path will be correct, but when Visual Studio 2019 is installed, the actual path to MSBuild binaries switches to ...\Current\...

The fix should be relatively simple

## Context

Running a comprehensive build script on .Net solutions, cascading steps to Update/Build/Package/Publish.

## Your Environment

* Module version used: 4.8.0
* Operating System and PowerShell version:
Windows Server 2016 Standard, Version 10.0.14393
PowerShell:
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  2879

**Comment by bryanroscoe** [comment]
I am also having this problem with just VS 2019 installed on Windows 10 1803. Happens on both pro and enterprise.

**Comment by devblackops** [comment]
Thanks for submitting the issue @dkorzhin. I'll dig into this.

**Comment by jimitndiaye** [comment]
Not sure if this is the same problem but I just instaled v4.8.0 and I now get the following when starting a build: 

>  No .NET Framework installation directory found at C:\Program Files
                              (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\amd64.
The path seems identical to that mentioned by @dkorzhin

**Comment by jozefizso** [comment]
We use the `Framework "4.6"` setting in psake and have Visual Studio 2019 only installed.

```
InstanceId          : 7a61b1f9
DisplayName         : Visual Studio Professional 2019
InstallationVersion : 16.1.29102.190
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
InstallDate         : 15. 7. 2019 16:47:40
```

psake will fail with error message:

```
psake.4.8.0\tools\psake\public\Assert.ps1:69 char:9 +         throw ('Assert: {0}' -f $failureMessage) +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Assert: No .NET Framework installation directory found at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\amd64.
```
