### ISSUE TITLE
Add support for .net 4.8

### ISSUE THREAD

**Issue by granit1986** [psake/psake#280]
## Expected Behavior
.net 4.8 is out, and would like to have psake support builds with the same

## Current Behavior
currently there is support for upto .net 4.7.2

## Possible Solution
PR attached.
added 4.8 to list of supported frameworks, with msbuild 15.0

## Context
We currently use psake for build scripting, and are looking to upgrade to .net 4.8
however, we only can upgrade to .net 4.7.2

## Your Environment
* Module version used:
* Operating System and PowerShell version:

**Comment by granit1986** [comment]
@devblackops When we can wait a new version with this changes?

**Comment by granit1986** [comment]
@devblackops Could you update PS Library, please

**Comment by granit1986** [comment]
@devblackops Could you update PS Gallery, please

**Comment by devblackops** [comment]
Sorry for the long delay!

psake `v4.9.0` has been released to the [PSGallery](https://www.powershellgallery.com/packages/psake/4.9.0), [Chocolatey](https://chocolatey.org/packages/psake/4.9.0), and [NuGet](https://www.nuget.org/packages/psake/4.9.0)!
