### ISSUE TITLE
Have any due date for a new release?

### ISSUE THREAD

**Issue by espiatsundiogroup** [psake/psake#286]
## Context
We have some computer with only has installed VS 2019 and our projects using a psake to build the projects

## Problem
If we try to build a project with a machine only have VS2019 have problems because search a msbuild targets doesn't exists.

## Question
I see, current code in GitHub in master branch solve our problem. Has a due date for a new release with current code?

## Environment
Module version used: 4.7.4
Operating System and PowerShell version: Windows 10, PowerShel 5.1 and VS2019

**Comment by devblackops** [comment]
Sorry for the long delay!

psake `v4.9.0` has been released to the [PSGallery](https://www.powershellgallery.com/packages/psake/4.9.0), [Chocolatey](https://chocolatey.org/packages/psake/4.9.0), and [NuGet](https://www.nuget.org/packages/psake/4.9.0)!
