### ISSUE TITLE
Overwrite included Task dependencies

### ISSUE THREAD

**Issue by blindzero** [psake/psake#298]
The primary goal was the following:
* I have different environments, one AppVeyor CI/CD, one "manual" executing build tasks from local shell
* when running the Task manually (e.g. TestIntegration), I want to have it depending from Build, Analyze, ...
* when running the Task in AppVeyor, I want it to have _no_ dependency as AppVeyor itself separates between build_script and test_script. When running TestIntegration with the dependency it would build two times (once in build_script and once in TestIntegration through this dependency
* I wanted to
  * define "TestIntegration" task without dependency in a separate file
  * separate two different psakeFile.ENVIRONMENT.ps1 for the Invoke-PSake
  * Include TestIntegration.ps1 in one of the psakeFile's as-is
  * Include TestIntegration.ps1 in the other psakeFile and set additional dependency

## Expected Behavior
* Defining PSake Tasks in other files "psake.MyTask.ps1"
```powershell
Task MyTask {
   Do-Something
}
```
* Include PSake Task file
```powershell
Include psake.MyTask.ps1
```
* Add additional dependency
```powershell
Task MyTask {} -Depends OtherTask
```

## Current Behavior
Doing this above brings up an error:
```powershell
WindowsPowerShell\Modules\psake\4.9.0\public\Assert.ps1:69 char:9 +         throw ('Assert: {0}' -f $failureMessage) +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Assert: Task compile has already been defined.
```

## Steps to Reproduce (for bugs)
see expected behaviour 

## Your Environment
* Module version used: 4.9.0
* Operating System and PowerShell version: Win 10 1909 PS 5.1

**Comment by UberDoodles** [comment]
What you're trying to do can already be achieved. Our psake build scripts are set up to do similar things.

`Task Build {
    Build-Stuff
}

Task Analyze {
    Analyze-Stuff
}

Task MyTask {
    Do-Something
}

Task MyLocalTask -Depends Build,Analyze,MyTask {}`

When running locally, you will run the MyLocalTask, but AppVeyor would run MyTask.

**Comment by blindzero** [comment]
Hi @UberDoodles 
thanks for that reply...yeah would work.
I wanted to avoid to have different names again and wanted simply to use Includes but...accepted ;)
Thanks,
M.
