### ISSUE TITLE
Include with parameter wildcard or foreach

### ISSUE THREAD

**Issue by blindzero** [psake/psake#299]
I want to include multiple files into my PSakeFile.
Wildcards, Parameters and Foreach are not working.

## Expected Behavior
Using one or any of the following should work and perform Include of file
```powershell
Include path\psakeTasks.*.ps1
Include $psakeTaskFile
Foreach ($file in $psakeIncludes) {
   Include $file
}
```

## Current Behavior
1. and 2. brings an error that the given file cannot be found.
3. is simply ignored / not executed

## Additional context
$psakeTaskFile and $psakeIncludes were parameters that were passed by
```powershell
$psakeTaskFile = "psakeTask.ps1"
$psakeIncludes = (Join-Path -Path "." -ChildPath "psakeTask.*.ps1")
$psakeParameters = @{"psakeTaskFile"=$psakeTaskFile;"psakeIncludes"=$psakeIncludes}
Invoke-PSake -parameter $psakeParameters
```
where $psakeTaskFile and $psakeIncludes itself work, the assembled HashTable $psakeParameters is fine as well.

## Context
At some point PSake tasks may get numberous and I want to split them up into many.
Avoiding errors by defined naming in Include some ForEach would be great, as well as wildcards etc.

**Comment by UberDoodles** [comment]
I have a separate issue #289 open which should enable you to do something very similar to your examples 1. and 3. I've got a pull request open for it. It would look something like this 

`Get-Item ".\psakeTasks.*.ps1" | Include`

The added benefit of this approach is that you can further manipulate or filter the items in the pipeline. Although admittedly, I don't foresee any use cases for that.

I'm not sure why your example 2. doesn't currently work though.

**Comment by blindzero** [comment]
Hi @UberDoodles 
that sounds pretty good if that would be possible and would help already a lot.
About my example #2 (passing a variable)...honestly I don't know, maybe this is more about usage as it just seems that the parameter is not "arriving" within my psakeFile although I am doing the invocation exactly as explained above.

**Comment by UberDoodles** [comment]
Thought it was also worth mentioning; it is possible to do what you're attempting in examples 1. and 3. currently, it's just a bit less concise. I think you can currently do something like this

```
Get-Item ".\psakeTasks.*.ps1" | ForEach-Object {
    Include $_
}
```
or
```
$files = Get-Item ".\psakeTasks.*.ps1"
ForEach ($file in $files) {
    Include $file
}
```

**Comment by blindzero** [comment]
Ok maybe going this way.
I am still wondering way my #2 is not working although it should and although your second example is as my#3 except that you gather $files inside your PsakeFile and I am doing outside to pass it in via -parameters.
