### ISSUE TITLE
No .NET Framework installation directory found

### ISSUE THREAD

**Issue by tobimax** [psake/psake#3]
Hi, When running the samples, i get the following.

No .NET Framework installation directory found at \Microsoft.NET\Framework64\v3.5\

I also get this for .NET 4.0 on other projects - Running Win 7 x64.

Thanks

Tobi.

**Comment by InterConectDigital** [comment]
Hello I use psake with visual studio on windows 10 and it works correctly, but when I use it on windows 11 it returns this error below. Does anyone know how to change visual studio path in psake

diretory vs windows 11 => C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.

![Screenshot_1](https://user-images.githubusercontent.com/53632931/157524907-9472df84-01b4-41cb-a6a5-263b47bb4146.png)
