### ISSUE TITLE
Github Releases and Tags did not match changelog

### ISSUE THREAD

**Issue by lanwin** [psake/psake#302]
As I now want to update our internal version of Psake. I stuck at the release page witch only lists version v4.7.4 witch is from 2018. So I looked at at the tags. But the last tag is also v4.7.4. I can see that there are to more versions in changelog. But where can I find its tags/commits?

Can you please push the tags and add releases in github so the github releases matches the changelog.md.

**Comment by gep13** [comment]
@lanwin thanks for bringing this up!

I have just updated the Releases section to match the information that is in the changelog.

Please let me know if there is anything else that needs to be done.

**Comment by lanwin** [comment]
Looks pretty good. Thank you!

**Comment by devblackops** [comment]
Thanks @gep13!
