### ISSUE TITLE
RequiredVariables argument is ignored when task has no action argument

### ISSUE THREAD

**Issue by lulle2007200** [psake/psake#307]
The RequiredVariables argument of a Task seems to be ignored when it doesnt perform an action by itself (e.g. it doesnt have an action script block).

Not sure if this is intended.

## Expected Behavior
Task without action block should throw an error if a Variable listed in `RequiredVariables` is not set

## Current Behavior
Task does not throw an error in that case.

## Steps to Reproduce (for bugs)
`Task ThisDoesNotFail -RequiredVariables NotDefined`

`Task ThisDoesFail -RequiredVariables NotDefined -Action { }`

## Your Environment

* Module version used: 4.9.1
* Operating System and PowerShell version: Win10/5.1

**Comment by devblackops** [comment]
Thanks for the issue @lulle2007200.

This should be fixed in https://github.com/psake/psake/commit/51427c6911dbab6ae2231d42d58ea9a3f0b52d66
