### ISSUE TITLE
Parameters to psake cmdlets are camelCase, not PascalCase

### ISSUE THREAD

**Issue by fgodskesen** [psake/psake#308]
## Expected Behavior
Most other PowerShell modules use PascalCase naming convention for named parameters in cmdlets.

e.g. see discussion here:
https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/36#issuecomment-110526891

or the official MS style guide
https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/strongly-encouraged-development-guidelines?view=powershell-7.1

## Current Behavior
parameters are in camelCase, as seen when running 
Get-Help Task

## Possible Solution
Refactor parameters to PascalCase. Should not be breaking change as PowerShell is case insensitive, but Intellisense would then suggest PascalCase parameters instead of camelCase.

## Context
Annoyance / Visual

## Your Environment
PowerShell 7.1.1
psake 4.9.0

**Comment by devblackops** [comment]
Thanks for the issue @fgodskesen. Indeed, the parameters _should_ be PascalCase. It's been on my TODO list for a while. I'll get it prioritized for the next release.
