### ISSUE TITLE
Invocation from wsl with list of tasks

### ISSUE THREAD

**Issue by krista-prokop** [psake/psake#327]
I have a psake file that i successfully invoke from powershell with this command, executing 3 tasks:
`.\buildScript.ps1 -TaskList Foo, Bar, Bat`

From wsl how do I pass the list of tasks?

One task works fine:
`powershell.exe -File "./buildScript.ps1" -TaskList Foo`

But multiple tasks doesn't:
`powershell.exe -File "./buildScript.ps1" -TaskList Foo,Bar`
Exception: Assert: Task Foo,Bar does not exist.

I've tried many variations of passing the task list  - with and without commas, quotes, brackets, etc. What's the correct way to do this? Thanks!

**Comment by HeyItsGilbert** [comment]
This is 2 years old, but incase you want to try something in the future. Try `powershell.exe -File "./buildScript.ps1" -TaskList @('Foo','Bar')`. I believe WSL is turning that into a single string.

**Comment by krista-prokop** [comment]
@HeyItsGilbert fantastic, ty for responding! I have just been using `powershell.exe -File "./buildScript.ps1" -Task foo && powershell.exe -File "./buildScript.ps1" -Task bar`
