### ISSUE TITLE
[Feature Request]: Add a -DisplayName parameter to the Task function

### ISSUE THREAD

**Issue by fourpastmidnight** [psake/psake#330]
## Summary

While psake provides the `FormatTaskName` function, this still falls short of allowing build script authors to customize their task name output while also constructing a tree of tasks and their dependencies. I would like to have readable output that means something to people reading the build log, but without them having to know intimate internal details of the overall build process, until/if/unless they want to go looking.

Now, there's nothing stopping me from using a task name such as the following, since the `-Name` parameter is a simple string:

```powershell
Task 'Prepare for build...' {
    # Do stuff here
}
```

However, where this gets a bit _unwieldy_ is when other tasks depend on another task, e.g.:

```powershell
Task 'Prepare for build...' {
    # Do stuff here
}

Task 'Building...' -DependsOn 'Prepare for build...' {
   # Build it!
}
```

## Possible Solution

As alluded to in the title, add a `-DisplayName` parameter to the `Task` function which is used to display the task name. Note that this does not preclude/obviate the need for `FormatTaskName`, as that function can still be used to apply additional formatting to the name, if desired. This additional parameter would be optional, falling back to the task's `-Name` if no value is provided, which also provides for backward compatibility with existing build scripts.

For example:

```powershell
FormatTaskName {
    Param (
        [string] $TaskDisplayName
    )

    $RuleLine = '-'*80
    Write-Host "$RuleLine`n    $TaskDisplayName...`n$RuleLine" -ForegroundColor Blue
}

Task Init -DisplayName 'Prepare for build' {
    # Do some initialization stuff here
}

Task Build -DisplayName 'Building' -DependsOn Init {
    # Build it!
}
```

## Context

This is mostly a cosmetic change that gives build script/system authors a little more flexibility on how information is output during the build process. The best way to currently achieve this would be to use a dictionary to map the task name to the desired display name; then in the `FormatTaskName` function, lookup the task's display name. However, it would be much simpler to let build script authors specify this parameter, if desired, to display the currently executing task.

## Your Environment

* Module version used: 4.9.0
* Operating System and PowerShell version: Win10, PS 5.1, PS 7.3, PS 7.4 (preview); Manjaro, PS 7.4 (preview)

**Comment by fourpastmidnight** [comment]
I failed to see that there is already defined a `-Description` parameter on the `Task` function. I wonder how people use that parameter? Is it displayed, if used? (Rhetorical question--I will try it and find out.) If so, perhaps this can take the place of the proposed `-DisplayName` parameter? Or perhaps they serve different purposes after all? Thoughts, comments?

**Comment by WithHolm** [comment]
I feel like im late to the party here, but for future reference:
I was thinking the same thing, but i figured out that there is a "FormatTaskName" function that formats the default "Executing {yourtask}" to write whatever you want. 
You can either define a format string or a scriptblock (this is where the magic happens).
if you combine this scriptblock with Get-PSakeScriptTasks you can get both alias and description data and show this instead if the taskname:
``` powershell
task default -depends mytask 

FormatTaskName {
    param($taskName)

    #get tasklist for current psake build script
    $task = Get-PSakeScriptTasks $psake.build_script_file|? Name -eq $taskName

    $arr = @()

    #set alias instead of name if defined
    if($task.alias){
        $arr += $task.alias
    }
    else{
        $arr += $taskName
    }

    #set description if defined
    if($task.description){
        $arr += $task.description
    }

    #join so you get "x:y"
    $out = $arr -join " -> "

    write-host "----$out---" -foregroundcolor blue
}

task mytask -description "my task description" -alias "my task alias" {
    "my task process log"
}
``` 

the output would look something like
``` text
psake version 4.9.0
Copyright (c) 2010-2018 James Kovacs & Contributors

----my task alias -> my task description---

my task process log

psake succeeded executing psakefile.ps1
```

hope this helps!

**Comment by HeyItsGilbert** [comment]
> I failed to see that there is already defined a `-Description` parameter on the `Task` function. I wonder how people use that parameter? Is it displayed, if used? (Rhetorical question--I will try it and find out.) If so, perhaps this can take the place of the proposed `-DisplayName` parameter? Or perhaps they serve different purposes after all? Thoughts, comments?

Your build script could have a `-Help` switch, which could call something like:
```powershell
Get-PSakeScriptTasks -buildFile $psakeFile |
        Format-Table -Property Name, Description, Alias, DependsOn
```

This is exactly what Stucco does which I really like  https://github.com/devblackops/Stucco/blob/main/build.ps1#L49-L52

**Comment by WithHolm** [comment]
> > I failed to see that there is already defined a `-Description` parameter on the `Task` function. I wonder how people use that parameter? Is it displayed, if used? (Rhetorical question--I will try it and find out.) If so, perhaps this can take the place of the proposed `-DisplayName` parameter? Or perhaps they serve different purposes after all? Thoughts, comments?
> 
> Your build script could have a `-Help` switch, which could call something like:
> 
> ```powershell
> Get-PSakeScriptTasks -buildFile $psakeFile |
>         Format-Table -Property Name, Description, Alias, DependsOn
> ```
> 
> This is exactly what Stucco does which I really like https://github.com/devblackops/Stucco/blob/main/build.ps1#L49-L52

this can also be done with the -docs switch on invoke-psake :)

**Comment by HeyItsGilbert** [comment]
Cleaning up issues. If the solutions specified don't suffice @fourpastmidnight feel free to reopen.
