### ISSUE TITLE
How Do I Get Psake to Return Non-Zero Return Code on Build Failure

### ISSUE THREAD

**Issue by bjmarte** [psake/psake#58]
We can't figure out the proper way to get the newer versions of Psake tor return an error code when the build fails.  We need this to happen in order to correctly integrate with our CI system (cruisecontrol.net, but I think it would be the same problem with any CI tool).  All of the Wiki articles about integrating with CI tools are either way out of date or just don't make sense to us.  We had to modify the end of the catch block in the "Invoke-psake" method as follows:

Before Modification:

```
    if (!$psake.run_by_psake_build_tester) {
        # if we are running in a nested scope (i.e. running a psake script from a psake script) then we need to re-throw the exception
        # so that the parent script will fail otherwise the parent script will report a successful build 
        $inNestedScope = ($psake.context.count -gt 1)
        if ( $inNestedScope ) {
            throw $_
        } else {
            Write-ColoredOutput $error_message -foregroundcolor Red
        }

    }
```

After Modification:

```
            throw $_
```

We could probably add back in the part about the build tester, I think the issue is with the nested scope, but we are using the tester so we stopped tweaking after we got correct failures.  

Is psake just not meant to return the error all the way out?  Is there some magic property to set to get this to happen?  I've seen mention of magic properties in a few articles but they are all old and we couldn't find references to such properties in the actual code.

**Comment by earldean** [comment]
I am using Jenkins, and I had this problem.  When an error occurs I use exec { cmd /c exit (1) }

Jenkins does not fail when exceptions are thrown from a Psake script.

**Comment by drinkbird** [comment]
@JamesDawson Thanks for the solution.

I'm using a script to bootstrap psake and invoke the actual build script. Adding `exit (!$psake.build_success)` as a last statement of the bootstrapper script did the trick.

**Comment by Midacts** [comment]
@drinkbird Learning about the $psake variable and your reply helped me figure out my TFS wohs.
Thanks for your help.

**Comment by drinkbird** [comment]
Much appreciated @Midacts :)

**Comment by kapslockkaps** [comment]
Please Help

I am getting below error in deploy.ps1 script, We are generating web.config through Psake automation.

15:13:10.297  +     Invoke-XmlPreprocess "$releaseArtifacts/$webName/Web.Config" $configurationE ...
15:13:10.297  +      
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] 
Exception: Cannot validate argument on parameter 'private:configFile'.
 The " Test-Path $_ -PathType Leaf " validation script for the argument with value
 "D:\GoAgent\pipelines\Dev\ReleaseArtifacts/Folder/Web.Config" did not return a result of True.
 Determine why the validation script failed, and then try the command again. --> 
 The " Test-Path $_ -PathType Leaf " validation script for the argument with value
 "D:\GoAgent\pipelines\Dev\ReleaseArtifacts/Folder/Web.Config" did not return a result of True. 
Determine why the validation script failed, and then try the command again.
