### ISSUE TITLE
Doesn't work with Visual studio 2013

### ISSUE THREAD

**Issue by mattwoberts** [psake/psake#76]
As per http://timrayburn.net/blog/visual-studio-2013-and-msbuild/

Visual studio 2013 now sticks msbuild in `C:\Program Files (x86)\MSBuild\12.0\Bin` (on my machine). That's where MSbuild should be run from now, and not the old location (`C:\Windows\Microsoft.NET\Framework64\v4.0.30319\`). Running it from the old location causes errors with missing .target files.

**Comment by jeremyabbott** [comment]
@damianh was @MortenSkjoldager's issue resolved? I'm encountering the same issue trying to clean a solution on a machine with psake 4.3 and VS2013. Psake tries to find MSBuild in c:\Program Files\MSBuild\Microsoft\Visual Studio\v11.0...

Thanks in advance.

**Comment by damianh** [comment]
Current version is 4.4.1, please verify problem exists with that.

**Comment by jeremyabbott** [comment]
I actually tried it first with 4.4.1, and received the same error. The only difference was that psake 4.3 moved onto the next task, and 4.4.1 stopped after the failure.
![capture](https://cloud.githubusercontent.com/assets/991806/6052415/48511d14-ac98-11e4-8dd3-a242143fe641.PNG)

**Comment by damianh** [comment]
I dont believe this has anything to do with psake.

http://stackoverflow.com/questions/17433904/v11-0-webapplications-microsoft-webapplication-targets-was-not-found-when-file-a

https://www.nuget.org/packages/MSBuild.Microsoft.VisualStudio.Web.targets/

**Comment by benguenter** [comment]
Should psake find the msbuild exe in the new directory? Or perhaps have an option to specify the msbuilld location?



Thanks,
Ben Guenter
Software Developer

**Comment by damianh** [comment]
It's finding msbuild.exe just fine; it's not finding that targets file.

http://stackoverflow.com/a/20095260

**Comment by jeremyabbott** [comment]
@damianh that's the issue. Our csproj files are referencing old msbuild data. Thank you for the help. I'm sorry for the inconvenience!
