### ISSUE TITLE
How should I use psake NuGet package?

### ISSUE THREAD

**Issue by vorou** [psake/psake#93]
I'd like to reference psake in my project through NuGet to be able to update it easily. However, I'd also like to have some kind of `just-run-this-file-and-everything-will-build.cmd` somewhere it can be easily found (i.e., in root dir of a project). 

As for now, NuGet puts psake stuff into `solution-dir\packages\psake.4.3.1.0\tools`. The version part will obviously change, so how should my `runner.cmd` looks like?

UPD: I mean, there's a way to just use whatever version exists through simple logic (take whatever matched `psake*` and use it), but I wonder if there's a simpler way to do it.

**Comment by ccbuilds** [comment]
I know this is a bit dated, but you could create folders at the solution level and put any scripts that need referencing in there. I am happy to if needed.
