### ISSUE TITLE
Add support for Parallel Tasks (using PowerShell 3.0 Workflows as back-end)

### ISSUE THREAD

**Issue by maximpashuk** [psake/psake#97]
Psake for now based on Powershell 2.0 and does not support parallel tasks at all.

Parallel tasks is very desired feature, making psake really first-class build system.
The only feature in PowerShell that support parallelism is workflows.
Workflows available since PowerShell 3.0.

So there only way I see to support parallel tasks is to migrating to PowerShell 3.0 and using workflows as back-end abstraction for parallel tasks.

**Comment by giggio** [comment]
I like this idea a lot.

**Comment by giggio** [comment]
Output could be:

````
Task A: whatever output
Task B: whatever output
````

**Comment by JonathanWilkins** [comment]
Could really use this can think of many instances that we can use it

**Comment by damianh** [comment]
Well does someone want to try implementing it so? :wink:

**Comment by vors** [comment]
Workflows can be overkill. 
Maybe can be achieved with https://github.com/RamblingCookieMonster/Invoke-Parallel

**Comment by sweeneyrobb** [comment]
are there any thoughts on how one would build and/or compose parallel tasks? `task Default -parallelDepends t1, t2, t3`?

**Comment by sweeneyrobb** [comment]
i just had a thought about this. without proper testing, i don't believe that the `$psake` global and anything bolted onto it (e.g. `$psake.context`) is safe for concurrency. One might need to copy the variable and pass into an invocation of `Invoke-Task`.

Maybe the easiest thing to do is to created nested calls to `Invoke-psake` inside of a `Start-Job`. i added a PR #152 to show what an example might look like at a Task level.

**Comment by gep13** [comment]
@sweeneyrobb this seems like a sensible approach to me, and fits in with the existing infrastructure.

**Comment by sweeneyrobb** [comment]
@gep13 thanks! I'll put together another PR. Thanks for the response.

**Comment by maximpashuk** [comment]
@gep13 thanks, I think your solution is well enough/
Start-Job\Wait-Job\Receive-Job combination allows to run tasks as parallel.

I close my issue, I think it is already resolved.

**Comment by gep13** [comment]
@maximpashuk glad to hear that you were able to make progress and thanks for following up by closing the issue.

**Comment by hyankov** [comment]
Correct me if I'm wrong, if you do `Start-Job` you are losing the imported modules in the current session and the code sample assumes that psake is loaded prior to all that. While usually in the real world you'd have something like:

`powershell.exe -Version 2 -NoProfile -ExecutionPolicy unrestricted -Command "& {cls; Import-Module '.\psake\psake.psm1'; invoke-psake .\build.ps1 `

**Comment by dmarlow** [comment]
Yes, you lose a lot using jobs. Take a look here for an alternative approach: https://github.com/RamblingCookieMonster/Invoke-Parallel/issues/15
